import { AfterViewInit, Component, OnDestroy, ViewChild } from '@angular/core';
import { HeroCardsComponent } from './hero-cards/hero-cards.component';
import { ButtonsHeaderComponent } from '../shared/components/buttons-header/buttons-header.component';
import {
  CardsSectionComponent,
  CardsSectionOptions,
} from '../shared/components/cards-section/cards-section.component';
import { HeaderButton } from '../shared/components/buttons-header/buttons-header.component';
import { TmdbEntityForCard } from '../shared/components/card/card.component';

@Component({
  selector: 'app-home',
  standalone: true,
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
  imports: [ButtonsHeaderComponent, HeroCardsComponent, CardsSectionComponent],
})
export class HomeComponent implements AfterViewInit, OnDestroy {
  protected userPhoto: string = '';

  private tmdbEntities = {
    persons: [
      {
        adult: false,
        gender: 1,
        id: 1254975,
        known_for_department: 'Acting',
        name: 'Shin Hyun-been',
        original_name: '신현빈',
        popularity: 273.428,
        profile_path: '/ajYk4UgT4hYCvfo0LA1SFJt9mTU.jpg',
        known_for: [
          {
            backdrop_path: '/lkUYS8K3tqOJsYHCKSWIMbG7ptj.jpg',
            id: 571625,
            title: 'The Closet',
            original_title: '클로젯',
            overview:
              "After moving into a new house, a young girl begins displaying strange and disturbing behavior until, one day, she disappears behind a closet. While the devastated father is left with no clue about his daughter's disappearance, an exorcist shows up to help.",
            poster_path: '/W2tus8EwEagKCCCPqqocHEM9F2.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'ko',
            genre_ids: [27, 53],
            popularity: 19.081,
            release_date: '2020-02-05',
            video: false,
            vote_average: 7.276,
            vote_count: 174,
          },
          {
            backdrop_path: '/1yqVaDR7uIA3Xx9GQIhbEbh5pEe.jpg',
            id: 571648,
            title: 'Beasts Clawing at Straws',
            original_title: '지푸라기라도 잡고 싶은 짐승들',
            overview:
              'A struggling restaurant owner, caring for his sick mom, finds a bag of cash in a sauna locker, while a customs officer gets into trouble when his girlfriend runs off with money he borrowed from a loan shark.',
            poster_path: '/7roaNIjNHMitbiNX0uEIFcwy6Cb.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'ko',
            genre_ids: [9648, 53, 80, 18],
            popularity: 19.146,
            release_date: '2020-02-19',
            video: false,
            vote_average: 7.119,
            vote_count: 235,
          },
          {
            backdrop_path: '/jG8mKDxe0LIDFBPB8uCeYGSBWCH.jpg',
            id: 153496,
            name: 'Reborn Rich',
            original_name: '재벌집 막내아들',
            overview:
              'After ten years, a loyal employee is framed for embezzlement, then murdered by his employers, only to be reborn as their youngest son, with a yearn for revenge guiding his hostile takeover. based on a hit novel.',
            poster_path: '/ioywelRYOfNJ5w8aNQ5ttJo9dk1.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'ko',
            genre_ids: [18, 10765],
            popularity: 138.181,
            first_air_date: '2022-11-18',
            vote_average: 7.882,
            vote_count: 76,
            origin_country: ['KR'],
          },
        ],
      },
      {
        adult: false,
        gender: 1,
        id: 1696016,
        known_for_department: 'Acting',
        name: 'Chloe Coleman',
        original_name: 'Chloe Coleman',
        popularity: 210.827,
        profile_path: '/rTbVFZMvUViFCIa5AXlBX3P6vfR.jpg',
        known_for: [
          {
            backdrop_path: '/eEF40Xk2twM3WjRNZftfo771gjv.jpg',
            id: 700391,
            title: '65',
            original_title: '65',
            overview:
              '65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth, must fend off dinosaurs to reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.',
            poster_path: '/rzRb63TldOKdKydCvWJM8B6EkPM.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [878, 28, 12, 53],
            popularity: 62.105,
            release_date: '2023-03-02',
            video: false,
            vote_average: 6.008,
            vote_count: 2211,
          },
          {
            backdrop_path: '/4xIBM8RwIvpwMlJSoF6tqFOaB6N.jpg',
            id: 592834,
            title: 'My Spy',
            original_title: 'My Spy',
            overview:
              'A hardened CIA operative finds himself at the mercy of a precocious 9-year-old girl, having been sent undercover to surveil her family.',
            poster_path: '/n2C6jRK9PtPIs99RQhKtqGlsnsO.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [10751, 28, 35],
            popularity: 156.48,
            release_date: '2020-01-09',
            video: false,
            vote_average: 6.886,
            vote_count: 1136,
          },
          {
            backdrop_path: '/oblUNeHlwV3VsjB5ITMlco5ZSOF.jpg',
            id: 493529,
            title: 'Dungeons & Dragons: Honor Among Thieves',
            original_title: 'Dungeons & Dragons: Honor Among Thieves',
            overview:
              'A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.',
            poster_path: '/v7UF7ypAqjsFZFdjksjQ7IUpXdn.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [12, 14, 35],
            popularity: 84.791,
            release_date: '2023-03-23',
            video: false,
            vote_average: 7.376,
            vote_count: 3276,
          },
        ],
      },
      {
        adult: false,
        gender: 1,
        id: 1679829,
        known_for_department: 'Acting',
        name: 'Frida Gustavsson',
        original_name: 'Frida Gustavsson',
        popularity: 184.47,
        profile_path: '/jtD5lJSSAc61AWCNKGlQmlyYNWv.jpg',
        known_for: [
          {
            backdrop_path: '/k47JEUTQsSMN532HRg6RCzZKBdB.jpg',
            id: 116135,
            name: 'Vikings: Valhalla',
            original_name: 'Vikings: Valhalla',
            overview:
              'In this sequel to "Vikings," a hundred years have passed and a new generation of legendary heroes arises to forge its own destiny — and make history.',
            poster_path: '/uCr7Ov7Rpzx0c0EPqbPcoEruTYl.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'en',
            genre_ids: [10759, 18, 10768],
            popularity: 1183.252,
            first_air_date: '2022-02-25',
            vote_average: 7.794,
            vote_count: 806,
            origin_country: ['US'],
          },
          {
            backdrop_path: '/97bwlJw220Z5XE3xAHF6G8gA8g6.jpg',
            id: 644124,
            title: 'Dampyr',
            original_title: 'Dampyr',
            overview:
              'In war-torn Balkans, bogus monster hunter Harlan Draka is hired by soldiers who happen to be under attack by an army of actual vampires, uncovering the hidden truth about his past in the process: he is half-human and half-vampire... a Dampyr.',
            poster_path: '/xdWjqmX4x0ObKIPqkr8Vptj99AZ.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'it',
            genre_ids: [27, 14, 28],
            popularity: 77.112,
            release_date: '2022-10-28',
            video: false,
            vote_average: 6.4,
            vote_count: 134,
          },
          {
            backdrop_path: '/skILeQ0wzeUERjfCmqii1MQ7kFW.jpg',
            id: 561605,
            title: 'Swoon',
            original_title: 'Eld & lågor',
            overview:
              'John and Ninni – both heirs to their own individual amusement parks – fall in love amidst the whirling world they both inhabit. A forbidden love and a war between their two families puts their love and loyalty to the test.',
            poster_path: '/teqb1t1awfRMqHkMdwIVF8INcqC.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'sv',
            genre_ids: [10749, 18],
            popularity: 7.972,
            release_date: '2019-02-14',
            video: false,
            vote_average: 6.15,
            vote_count: 20,
          },
        ],
      },
      {
        adult: false,
        gender: 1,
        id: 587208,
        known_for_department: 'Acting',
        name: 'Laura Berlin',
        original_name: 'Laura Berlin',
        popularity: 181.575,
        profile_path: '/2aOv5SH684DVJy2wGuLNdIhwBWE.jpg',
        known_for: [
          {
            backdrop_path: '/6NZMN7XRb0TDRloST3P8T9W2z0W.jpg',
            id: 175774,
            title: 'Ruby Red',
            original_title: 'Rubinrot',
            overview:
              'On her 16th birthday, Gwendolyn Shepherd finds out that instead of her cousin, she has inherited a rare gene that allows her to travel through time.',
            poster_path: '/lCfUO2be7jlskyTXRnf1bQtdIes.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'de',
            genre_ids: [14, 18, 10749],
            popularity: 22.23,
            release_date: '2013-03-14',
            video: false,
            vote_average: 6.966,
            vote_count: 1091,
          },
          {
            backdrop_path: '/k47JEUTQsSMN532HRg6RCzZKBdB.jpg',
            id: 116135,
            name: 'Vikings: Valhalla',
            original_name: 'Vikings: Valhalla',
            overview:
              'In this sequel to "Vikings," a hundred years have passed and a new generation of legendary heroes arises to forge its own destiny — and make history.',
            poster_path: '/uCr7Ov7Rpzx0c0EPqbPcoEruTYl.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'en',
            genre_ids: [10759, 18, 10768],
            popularity: 1183.252,
            first_air_date: '2022-02-25',
            vote_average: 7.794,
            vote_count: 806,
            origin_country: ['US'],
          },
          {
            backdrop_path: '/tdGCuUge9wZUYP785WTGVrMIxBk.jpg',
            id: 337556,
            title: 'Emerald Green',
            original_title: 'Smaragdgrün',
            overview:
              "Emerald Green is the stunning conclusion to Kerstin Gier's Ruby Red Trilogy, picking up where Sapphire Blue left off, reaching new heights of intrigue and romance as Gwen finally uncovers the secrets of the time-traveling society and learns her fate.",
            poster_path: '/hoQa869OPu5DqO5Qz1rQe0Gi9cs.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'de',
            genre_ids: [14, 28, 9648],
            popularity: 27.913,
            release_date: '2016-07-07',
            video: false,
            vote_average: 6.98,
            vote_count: 835,
          },
        ],
      },
      {
        adult: false,
        gender: 2,
        id: 64,
        known_for_department: 'Acting',
        name: 'Gary Oldman',
        original_name: 'Gary Oldman',
        popularity: 193.947,
        profile_path: '/2v9FVVBUrrkW2m3QOcYkuhq9A6o.jpg',
        known_for: [
          {
            backdrop_path: '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
            id: 155,
            title: 'The Dark Knight',
            original_title: 'The Dark Knight',
            overview:
              'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
            poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [18, 28, 80, 53],
            popularity: 145.235,
            release_date: '2008-07-16',
            video: false,
            vote_average: 8.5,
            vote_count: 32236,
          },
          {
            backdrop_path: '/c3OHQncTAnKFhdOTX7D3LTW6son.jpg',
            id: 49026,
            title: 'The Dark Knight Rises',
            original_title: 'The Dark Knight Rises',
            overview:
              "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
            poster_path: '/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 80, 18, 53],
            popularity: 102.244,
            release_date: '2012-07-17',
            video: false,
            vote_average: 7.8,
            vote_count: 22297,
          },
          {
            backdrop_path: '/6prkTmEEsB3f9hhKBzUePLe27b2.jpg',
            id: 399404,
            title: 'Darkest Hour',
            original_title: 'Darkest Hour',
            overview:
              'In May 1940, the fate of World War II hangs on Winston Churchill, who must decide whether to negotiate with Adolf Hitler or fight on knowing that it could mean the end of the British Empire.',
            poster_path: '/xa6G3aKlysQeVg9wOb0dRcIGlWu.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [18, 36],
            popularity: 31.264,
            release_date: '2017-11-22',
            video: false,
            vote_average: 7.351,
            vote_count: 4975,
          },
        ],
      },
      {
        adult: false,
        gender: 2,
        id: 85,
        known_for_department: 'Acting',
        name: 'Johnny Depp',
        original_name: 'Johnny Depp',
        popularity: 195.325,
        profile_path: '/wcI594cwM4ArPwvRd2IU0Z0yLuh.jpg',
        known_for: [
          {
            backdrop_path: '/wW7Wt5bXzPy4VOEE4LTIUDyDgBo.jpg',
            id: 22,
            title: 'Pirates of the Caribbean: The Curse of the Black Pearl',
            original_title:
              'Pirates of the Caribbean: The Curse of the Black Pearl',
            overview:
              "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
            poster_path: '/poHwCZeWzJCShH7tOjg8RIoyjcw.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [12, 14, 28],
            popularity: 217.769,
            release_date: '2003-07-09',
            video: false,
            vote_average: 7.8,
            vote_count: 20184,
          },
          {
            backdrop_path: '/vv5a8u6e40kyH0Hp6HuamAgzRai.jpg',
            id: 58,
            title: "Pirates of the Caribbean: Dead Man's Chest",
            original_title: "Pirates of the Caribbean: Dead Man's Chest",
            overview:
              'Captain Jack Sparrow works his way out of a blood debt with the ghostly Davy Jones to avoid eternal damnation.',
            poster_path: '/uXEqmloGyP7UXAiphJUu2v2pcuE.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [12, 14, 28],
            popularity: 189.121,
            release_date: '2006-07-06',
            video: false,
            vote_average: 7.4,
            vote_count: 15590,
          },
          {
            backdrop_path: '/bSvUW4JQ6g4QiKvwejcfcPRd4Ke.jpg',
            id: 118,
            title: 'Charlie and the Chocolate Factory',
            original_title: 'Charlie and the Chocolate Factory',
            overview:
              "A young boy wins a tour through the most magnificent chocolate factory in the world, led by the world's most unusual candy maker.",
            poster_path: '/iKP6wg3c6COUe8gYutoGG7qcPnO.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [12, 35, 10751, 14],
            popularity: 139.961,
            release_date: '2005-07-13',
            video: false,
            vote_average: 7.051,
            vote_count: 14844,
          },
        ],
      },
      {
        adult: false,
        gender: 2,
        id: 2786960,
        known_for_department: 'Acting',
        name: 'Gabriel Guevara',
        original_name: 'Gabriel Guevara',
        popularity: 153.494,
        profile_path: '/pviRYKEEmoPUfLYwP1VHJ6LQcRg.jpg',
        known_for: [
          {
            backdrop_path: '/lntyt4OVDbcxA1l7LtwITbrD3FI.jpg',
            id: 1010581,
            title: 'My Fault',
            original_title: 'Culpa mía',
            overview:
              "Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
            poster_path: '/w46Vw536HwNnEzOa7J24YH9DPRS.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'es',
            genre_ids: [18, 10749],
            popularity: 564.925,
            release_date: '2023-06-08',
            video: false,
            vote_average: 7.974,
            vote_count: 2722,
          },
          {
            backdrop_path: '/ieiq46OoeTrLkjtclmhii6iRyzP.jpg',
            id: 242876,
            name: 'Raising Voices',
            original_name: 'Ni una más',
            overview:
              'When a 17-year-old reports a sexual assault at her high school, an investigation upends her life and tests her relationships.',
            poster_path: '/lCU77Jp0iWN2e1WuSJvR7M35ebN.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'es',
            genre_ids: [18],
            popularity: 226.236,
            first_air_date: '2024-05-31',
            vote_average: 7.827,
            vote_count: 243,
            origin_country: ['ES'],
          },
          {
            backdrop_path: '/pmygxuqpZQmDAzGAba6wbDsHbR0.jpg',
            id: 1029528,
            title: 'Tomorrow Is Today',
            original_title: 'Mañana es hoy',
            overview:
              'A family is on holiday in 1991 when their teenage daughter decides to elope with her boyfriend. Their parents travel forward in time to 2022 and see how much Spain has changed in three decades.',
            poster_path: '/1rgf4MomMFjOdkskY6NYoHSy6uz.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'es',
            genre_ids: [35],
            popularity: 14.203,
            release_date: '2022-11-29',
            video: false,
            vote_average: 6.201,
            vote_count: 77,
          },
        ],
      },
      {
        adult: false,
        gender: 2,
        id: 976,
        known_for_department: 'Acting',
        name: 'Jason Statham',
        original_name: 'Jason Statham',
        popularity: 191.491,
        profile_path: '/whNwkEQYWLFJA8ij0WyOOAD5xhQ.jpg',
        known_for: [
          {
            backdrop_path: '/ibKeXahq4JD63z6uWQphqoJLvNw.jpg',
            id: 345940,
            title: 'The Meg',
            original_title: 'The Meg',
            overview:
              'A deep sea submersible pilot revisits his past fears in the Mariana Trench, and accidentally unleashes the seventy foot ancestor of the Great White Shark believed to be extinct.',
            poster_path: '/eyWICPcxOuTcDDDbTMOZawoOn8d.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 878, 27],
            popularity: 83.01,
            release_date: '2018-08-09',
            video: false,
            vote_average: 6.257,
            vote_count: 7473,
          },
          {
            backdrop_path: '/kWt1OcPgwO1ssu57wgTKmq38JYw.jpg',
            id: 4108,
            title: 'The Transporter',
            original_title: 'The Transporter',
            overview:
              'Former Special Forces officer Frank Martin will deliver anything to anyone for the right price, and his no-questions-asked policy puts him in high demand. But when he realizes his latest cargo is alive, it sets in motion a dangerous chain of events. The bound and gagged Lai is being smuggled to France by a shady American businessman, and Frank works to save her as his own illegal activities are uncovered by a French detective.',
            poster_path: '/v3QIFUWgtVN4wejVuDZowuyJ20W.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 80, 53],
            popularity: 45.693,
            release_date: '2002-10-02',
            video: false,
            vote_average: 6.705,
            vote_count: 5177,
          },
          {
            backdrop_path: '/70AV2Xx5FQYj20labp0EGdbjI6E.jpg',
            id: 637649,
            title: 'Wrath of Man',
            original_title: 'Wrath of Man',
            overview:
              "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
            poster_path: '/M7SUK85sKjaStg4TKhlAVyGlz3.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [80, 28, 12, 53],
            popularity: 126.532,
            release_date: '2021-04-22',
            video: false,
            vote_average: 7.64,
            vote_count: 5104,
          },
        ],
      },
      {
        adult: false,
        gender: 2,
        id: 1502483,
        known_for_department: 'Acting',
        name: 'Leo Suter',
        original_name: 'Leo Suter',
        popularity: 150.973,
        profile_path: '/vRFLpAz9k01M4TwEvgXao8AkXFf.jpg',
        known_for: [
          {
            backdrop_path: '/k47JEUTQsSMN532HRg6RCzZKBdB.jpg',
            id: 116135,
            name: 'Vikings: Valhalla',
            original_name: 'Vikings: Valhalla',
            overview:
              'In this sequel to "Vikings," a hundred years have passed and a new generation of legendary heroes arises to forge its own destiny — and make history.',
            poster_path: '/uCr7Ov7Rpzx0c0EPqbPcoEruTYl.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'en',
            genre_ids: [10759, 18, 10768],
            popularity: 1183.252,
            first_air_date: '2022-02-25',
            vote_average: 7.794,
            vote_count: 806,
            origin_country: ['US'],
          },
          {
            backdrop_path: '/xjotE7aFdZ0D8aGriYjFOtDayct.jpg',
            id: 102651,
            title: 'Maleficent',
            original_title: 'Maleficent',
            overview:
              "A beautiful, pure-hearted young woman, Maleficent has an idyllic life growing up in a peaceable forest kingdom, until one day when an invading army threatens the harmony of the land. She rises to be the land's fiercest protector, but she ultimately suffers a ruthless betrayal – an act that begins to turn her heart into stone. Bent on revenge, Maleficent faces an epic battle with the invading King's successor and, as a result, places a curse upon his newborn infant Aurora. As the child grows, Maleficent realizes that Aurora holds the key to peace in the kingdom – and to Maleficent's true happiness as well.",
            poster_path: '/bDG3yei6AJlEAK3A5wN7RwFXQ7V.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [14, 12, 28, 10751, 10749],
            popularity: 108.059,
            release_date: '2014-05-28',
            video: false,
            vote_average: 7.092,
            vote_count: 12882,
          },
          {
            backdrop_path: '/4KSOnimRKhEcT1cV3t8nd5NEeVQ.jpg',
            id: 283378,
            title: 'Fallen',
            original_title: 'Fallen',
            overview:
              'Lucinda Price is sent to a reform academy under the assumption that she has killed a boy. There, she meets two mysterious boys, Cam and Daniel, to whom she feels drawn to both. But as the love triangle unfurls, it is Daniel that Luce cannot keep herself away from, and things begin to take a darker turn when she finds out his true identity.',
            poster_path: '/k0na2JR3mIgl5m64tW5uxB5Fa4m.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [18, 14, 10749],
            popularity: 21.094,
            release_date: '2016-11-10',
            video: false,
            vote_average: 6.12,
            vote_count: 1551,
          },
        ],
      },
      {
        adult: false,
        gender: 1,
        id: 1245,
        known_for_department: 'Acting',
        name: 'Scarlett Johansson',
        original_name: 'Scarlett Johansson',
        popularity: 176.215,
        profile_path: '/6NsMbJXRlDZuDzatN2akFdGuTvx.jpg',
        known_for: [
          {
            backdrop_path: '/ozVwXlfxqNsariipatGwa5px3Pm.jpg',
            id: 240832,
            title: 'Lucy',
            original_title: 'Lucy',
            overview:
              'A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.',
            poster_path: '/s678JxMMMDyj7TRSsK6hR2FTF7A.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'fr',
            genre_ids: [28, 878],
            popularity: 63.028,
            release_date: '2014-07-25',
            video: false,
            vote_average: 6.451,
            vote_count: 15730,
          },
          {
            backdrop_path: '/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg',
            id: 497698,
            title: 'Black Widow',
            original_title: 'Black Widow',
            overview:
              'Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.',
            poster_path: '/kwB7d51AIcyzPOBOHLCEZJkmPhQ.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 12, 878],
            popularity: 107.423,
            release_date: '2021-07-07',
            video: false,
            vote_average: 7.252,
            vote_count: 9931,
          },
          {
            backdrop_path: '/dDVqfmCzSy3TKSmiS2pJ9QB5E3P.jpg',
            id: 315837,
            title: 'Ghost in the Shell',
            original_title: 'Ghost in the Shell',
            overview:
              "In the near future, Major is the first of her kind: a human saved from a terrible crash, then cyber-enhanced to be a perfect soldier devoted to stopping the world's most dangerous criminals.",
            poster_path: '/myRzRzCxdfUWjkJWgpHHZ1oGkJd.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [878, 18, 28],
            popularity: 43.451,
            release_date: '2017-03-29',
            video: false,
            vote_average: 6.078,
            vote_count: 7851,
          },
        ],
      },
      {
        adult: false,
        gender: 1,
        id: 224513,
        known_for_department: 'Acting',
        name: 'Ana de Armas',
        original_name: 'Ana de Armas',
        popularity: 138.429,
        profile_path: '/3vxvsmYLTf4jnr163SUlBIw51ee.jpg',
        known_for: [
          {
            backdrop_path: '/ilRyazdMJwN05exqhwK4tMKBYZs.jpg',
            id: 335984,
            title: 'Blade Runner 2049',
            original_title: 'Blade Runner 2049',
            overview:
              "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
            poster_path: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [878, 18],
            popularity: 186.725,
            release_date: '2017-10-04',
            video: false,
            vote_average: 7.6,
            vote_count: 13282,
          },
          {
            backdrop_path: '/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg',
            id: 546554,
            title: 'Knives Out',
            original_title: 'Knives Out',
            overview:
              "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
            poster_path: '/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [35, 80, 9648],
            popularity: 86.419,
            release_date: '2019-11-27',
            video: false,
            vote_average: 7.849,
            vote_count: 12041,
          },
          {
            backdrop_path: '/oNoprEND25zXR6Fns8cIZUkuoMc.jpg',
            id: 308266,
            title: 'War Dogs',
            original_title: 'War Dogs',
            overview:
              "Based on the true story of two young men, David Packouz and Efraim Diveroli, who won a $300 million contract from the Pentagon to arm America's allies in Afghanistan.",
            poster_path: '/mDcPRjZC1bb6LavFU3gwsWdVfCM.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [35, 80, 18],
            popularity: 55.445,
            release_date: '2016-08-18',
            video: false,
            vote_average: 6.919,
            vote_count: 4767,
          },
        ],
      },
      {
        adult: false,
        gender: 2,
        id: 192,
        known_for_department: 'Acting',
        name: 'Morgan Freeman',
        original_name: 'Morgan Freeman',
        popularity: 171.316,
        profile_path: '/jPsLqiYGSofU4s6BjrxnefMfabb.jpg',
        known_for: [
          {
            backdrop_path: '/dYjZ27hDw2QFaEIfzbNGwW0IkV9.jpg',
            id: 807,
            title: 'Se7en',
            original_title: 'Se7en',
            overview:
              'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
            poster_path: '/6yoghtyTpznpBik8EngEmJskVUO.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [80, 9648, 53],
            popularity: 204.89,
            release_date: '1995-09-22',
            video: false,
            vote_average: 8.374,
            vote_count: 20583,
          },
          {
            backdrop_path: '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
            id: 278,
            title: 'The Shawshank Redemption',
            original_title: 'The Shawshank Redemption',
            overview:
              'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
            poster_path: '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [18, 80],
            popularity: 159.693,
            release_date: '1994-09-23',
            video: false,
            vote_average: 8.706,
            vote_count: 26483,
          },
          {
            backdrop_path: '/ozVwXlfxqNsariipatGwa5px3Pm.jpg',
            id: 240832,
            title: 'Lucy',
            original_title: 'Lucy',
            overview:
              'A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.',
            poster_path: '/s678JxMMMDyj7TRSsK6hR2FTF7A.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'fr',
            genre_ids: [28, 878],
            popularity: 63.028,
            release_date: '2014-07-25',
            video: false,
            vote_average: 6.451,
            vote_count: 15730,
          },
        ],
      },
      {
        adult: false,
        gender: 2,
        id: 2514293,
        known_for_department: 'Acting',
        name: 'Sam Corlett',
        original_name: 'Sam Corlett',
        popularity: 111.663,
        profile_path: '/9SQHs53DKbyn0JwdyxIeuiCiuYb.jpg',
        known_for: [
          {
            backdrop_path: '/k47JEUTQsSMN532HRg6RCzZKBdB.jpg',
            id: 116135,
            name: 'Vikings: Valhalla',
            original_name: 'Vikings: Valhalla',
            overview:
              'In this sequel to "Vikings," a hundred years have passed and a new generation of legendary heroes arises to forge its own destiny — and make history.',
            poster_path: '/uCr7Ov7Rpzx0c0EPqbPcoEruTYl.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'en',
            genre_ids: [10759, 18, 10768],
            popularity: 1183.252,
            first_air_date: '2022-02-25',
            vote_average: 7.794,
            vote_count: 806,
            origin_country: ['US'],
          },
          {
            backdrop_path: '/sGIfwDYvfU0h1G7pGWEhdEi9hT2.jpg',
            id: 567797,
            title: 'The Dry',
            original_title: 'The Dry',
            overview:
              'Aaron Falk returns to his drought-stricken hometown to attend a tragic funeral. But his return opens a decades-old wound - the unsolved death of a teenage girl.',
            poster_path: '/zM12bfL2TEqVRXjiQIFUWUMLcCg.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [80, 53, 9648],
            popularity: 45.353,
            release_date: '2021-01-01',
            video: false,
            vote_average: 6.829,
            vote_count: 618,
          },
          {
            backdrop_path: '/8AdmUPTyidDebwIuakqkSt6u1II.jpg',
            id: 79242,
            name: 'Chilling Adventures of Sabrina',
            original_name: 'Chilling Adventures of Sabrina',
            overview:
              'As her 16th birthday nears, Sabrina must choose between the witch world of her family and the human world of her friends. Based on the Archie comic.',
            poster_path: '/yxMpoHO0CXP5o9gB7IfsciilQS4.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'en',
            genre_ids: [9648, 10765, 18],
            popularity: 240.355,
            first_air_date: '2018-10-26',
            vote_average: 8.218,
            vote_count: 3464,
            origin_country: ['US'],
          },
        ],
      },
      {
        adult: false,
        gender: 2,
        id: 3157355,
        known_for_department: 'Acting',
        name: 'Wang Xingyue',
        original_name: '王星越',
        popularity: 111.883,
        profile_path: '/u3qToxRJ9ez5lCrutGfLTiKJhzI.jpg',
        known_for: [
          {
            backdrop_path: '/wnnewn1vKH9Wb1fVSdjREgK6sfG.jpg',
            id: 197107,
            name: 'Delicacies Destiny',
            original_name: '珍馐记',
            overview:
              "A talented and kind chef, Ling Xiaoxiao, is accepted into the delicacy role of chef in an Imperial palace thanks to the appreciative appetite of the Crown Prince, Zhu Shoukui. Set on becoming the best Imperial Chef, with the Prince's help, Ling tries to navigate the pitfalls of palace life while remaining true to her goals in the face of forbidden love.",
            poster_path: '/zVa92V94K9RNF2Odci4CRvtPd1X.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'zh',
            genre_ids: [18],
            popularity: 77.064,
            first_air_date: '2022-04-07',
            vote_average: 6.8,
            vote_count: 22,
            origin_country: ['CN'],
          },
          {
            backdrop_path: '/cvrVhAO17QH1KUU5jrejfNIgyIo.jpg',
            id: 236809,
            name: 'Scent of Time',
            original_name: '为有暗香来',
            overview:
              "A young woman's plan to marry the heir to a Chinese incense empire leads to her family's ruin...until she gets a second chance to right her wrongs.",
            poster_path: '/nNCZRUHF3uL7xU6MvkoIfPLuz2G.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'zh',
            genre_ids: [18],
            popularity: 74.942,
            first_air_date: '2023-10-13',
            vote_average: 7,
            vote_count: 9,
            origin_country: ['CN'],
          },
          {
            backdrop_path: '/nP458tk9snY2AJY3MtMb9orBqjK.jpg',
            id: 129117,
            name: 'One and Only',
            original_name: '周生如故',
            overview:
              'Zhou Sheng Chen was raised by his brother, the Emperor, until the age of thirteen, when he set out to defend the border and establish himself as a loyal and accomplished general. Cui Shi Yi, the well-read daughter of an esteemed family, has been betrothed to the Crown Prince since birth. However, political scheming and tragic events result in Cui Shi Yi falling mute, her former fiance becoming a child Emperor, and Zhou Sheng Chen returning to the capital amidst a cloud of political turmoil.',
            poster_path: '/iN8GBlkEdngye6igvqC2JQhgrZ7.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'zh',
            genre_ids: [18],
            popularity: 100.473,
            first_air_date: '2021-08-18',
            vote_average: 8.333,
            vote_count: 9,
            origin_country: ['CN'],
          },
        ],
      },
      {
        adult: false,
        gender: 1,
        id: 115440,
        known_for_department: 'Acting',
        name: 'Sydney Sweeney',
        original_name: 'Sydney Sweeney',
        popularity: 121.126,
        profile_path: '/qYiaSl0Eb7G3VaxOg8PxExCFwon.jpg',
        known_for: [
          {
            backdrop_path: '/9KnIzPCv9XpWA0MqmwiKBZvV1Sj.jpg',
            id: 85552,
            name: 'Euphoria',
            original_name: 'Euphoria',
            overview:
              'A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.',
            poster_path: '/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'en',
            genre_ids: [18],
            popularity: 318.301,
            first_air_date: '2019-06-16',
            vote_average: 8.321,
            vote_count: 9575,
            origin_country: ['US'],
          },
          {
            backdrop_path: '/j9eOeLlTGoHoM8BNUJVNyWmIvCi.jpg',
            id: 1072790,
            title: 'Anyone But You',
            original_title: 'Anyone But You',
            overview:
              'After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.',
            poster_path: '/5qHoazZiaLe7oFBok7XlUhg96f2.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [10749, 35],
            popularity: 259.921,
            release_date: '2023-12-21',
            video: false,
            vote_average: 7.028,
            vote_count: 1756,
          },
          {
            backdrop_path: '/3rwszCm4XyBtIWSjbUbgNwJOidu.jpg',
            id: 645710,
            title: 'The Voyeurs',
            original_title: 'The Voyeurs',
            overview:
              'When Pippa and Thomas move into their dream apartment, they notice that their windows look directly into the apartment opposite – inviting them to witness the volatile relationship of the attractive couple across the street. But what starts as a simple curiosity turns into full-blown obsession with increasingly dangerous consequences.',
            poster_path: '/8Y4XOIWhpOvSOEn8XrxbkH9yAXO.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [53],
            popularity: 58.157,
            release_date: '2021-08-25',
            video: false,
            vote_average: 6.615,
            vote_count: 856,
          },
        ],
      },
      {
        adult: false,
        gender: 1,
        id: 125025,
        known_for_department: 'Acting',
        name: 'Joey King',
        original_name: 'Joey King',
        popularity: 125.267,
        profile_path: '/b0diEOPPAxOOInWOP9koaqvqUvi.jpg',
        known_for: [
          {
            backdrop_path: '/aqrDUkuzksLhOD8pbyBXLO0dz5t.jpg',
            id: 454983,
            title: 'The Kissing Booth',
            original_title: 'The Kissing Booth',
            overview:
              "When teenager Elle's first kiss leads to a forbidden romance with the hottest boy in high school, she risks her relationship with her best friend.",
            poster_path: '/7Dktk2ST6aL8h9Oe5rpk903VLhx.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [10749, 35],
            popularity: 58.11,
            release_date: '2018-05-11',
            video: false,
            vote_average: 7.203,
            vote_count: 7115,
          },
          {
            backdrop_path: '/wO5QSWZPBT71gMLvrRex0bVc0V9.jpg',
            id: 583083,
            title: 'The Kissing Booth 2',
            original_title: 'The Kissing Booth 2',
            overview:
              'With college decisions looming, Elle juggles her long-distance romance with Noah, changing relationship with bestie Lee and feelings for a new classmate.',
            poster_path: '/mb7wQv0adK3kjOUr9n93mANHhPJ.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [35, 10749],
            popularity: 49.678,
            release_date: '2020-07-24',
            video: false,
            vote_average: 7.654,
            vote_count: 4934,
          },
          {
            backdrop_path: '/y2Ca1neKke2mGPMaHzlCNDVZqsK.jpg',
            id: 718930,
            title: 'Bullet Train',
            original_title: 'Bullet Train',
            overview:
              "Unlucky assassin Ladybug is determined to do his job peacefully after one too many gigs gone off the rails. Fate, however, may have other plans, as Ladybug's latest mission puts him on a collision course with lethal adversaries from around the globe—all with connected, yet conflicting, objectives—on the world's fastest train.",
            poster_path: '/j8szC8OgrejDQjjMKSVXyaAjw3V.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 35, 53],
            popularity: 121.032,
            release_date: '2022-08-03',
            video: false,
            vote_average: 7.468,
            vote_count: 5840,
          },
        ],
      },
      {
        adult: false,
        gender: 2,
        id: 6384,
        known_for_department: 'Acting',
        name: 'Keanu Reeves',
        original_name: 'Keanu Reeves',
        popularity: 129.094,
        profile_path: '/4D0PpNI0kmP58hgrwGC3wCjxhnm.jpg',
        known_for: [
          {
            backdrop_path: '/ncEsesgOJDNrTUED89hYbA117wo.jpg',
            id: 603,
            title: 'The Matrix',
            original_title: 'The Matrix',
            overview:
              'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
            poster_path: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 878],
            popularity: 121.374,
            release_date: '1999-03-31',
            video: false,
            vote_average: 8.216,
            vote_count: 25184,
          },
          {
            backdrop_path: '/ipyxbPJrLB1g9AfHq4xH5nLWmew.jpg',
            id: 245891,
            title: 'John Wick',
            original_title: 'John Wick',
            overview:
              'Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.',
            poster_path: '/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 53],
            popularity: 79.273,
            release_date: '2014-10-22',
            video: false,
            vote_average: 7.433,
            vote_count: 18817,
          },
          {
            backdrop_path: '/tHkujDqdPC9VQoFpEWU0QgWIZyM.jpg',
            id: 324552,
            title: 'John Wick: Chapter 2',
            original_title: 'John Wick: Chapter 2',
            overview:
              'John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.',
            poster_path: '/hXWBc0ioZP3cN4zCu6SN3YHXZVO.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 53, 80],
            popularity: 110.048,
            release_date: '2017-02-08',
            video: false,
            vote_average: 7.331,
            vote_count: 12750,
          },
        ],
      },
      {
        adult: false,
        gender: 1,
        id: 26723,
        known_for_department: 'Acting',
        name: 'Katheryn Winnick',
        original_name: 'Katheryn Winnick',
        popularity: 123.554,
        profile_path: '/vQSqH3ybDWZHZIqX4NZKhOCXAhQ.jpg',
        known_for: [
          {
            backdrop_path: '/lHe8iwM4Cdm6RSEiara4PN8ZcBd.jpg',
            id: 44217,
            name: 'Vikings',
            original_name: 'Vikings',
            overview:
              "The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.",
            poster_path: '/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'en',
            genre_ids: [10759, 18, 10768],
            popularity: 821.149,
            first_air_date: '2013-03-03',
            vote_average: 8.091,
            vote_count: 6770,
            origin_country: ['CA'],
          },
          {
            backdrop_path: '/lSCKo6QGJ88Gn3espNnvL87CinA.jpg',
            id: 483906,
            title: 'Polar',
            original_title: 'Polar',
            overview:
              'When a retiring assassin realizes that he is the target of a hit, he winds up back in the game going head to head with a gang of younger, ruthless killers.',
            poster_path: '/qOBEpKVLl8Q9CZScbOcRRVISezV.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 80, 18],
            popularity: 38.982,
            release_date: '2019-01-25',
            video: false,
            vote_average: 6.286,
            vote_count: 2132,
          },
          {
            backdrop_path: '/pVVobDO8cezhVPvwD6EBUN0g3mt.jpg',
            id: 353491,
            title: 'The Dark Tower',
            original_title: 'The Dark Tower',
            overview:
              'A boy haunted by visions of a parallel world aids its disillusioned guardian in preventing the destruction of the nexus of universes known as the Dark Tower.',
            poster_path: '/i9GUSgddIqrroubiLsvvMRYyRy0.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [14, 28, 878],
            popularity: 50.241,
            release_date: '2017-08-03',
            video: false,
            vote_average: 5.72,
            vote_count: 4946,
          },
        ],
      },
      {
        adult: false,
        gender: 1,
        id: 3295424,
        known_for_department: 'Acting',
        name: 'Ava Mendez',
        original_name: 'Ava Mendez',
        popularity: 107.485,
        profile_path: '/7copIlR1xIzE4KxTXj1N9CwNQlf.jpg',
        known_for: [
          {
            backdrop_path: '/ougkufYSiruP8jrEHQanXN7DxRv.jpg',
            id: 893694,
            title: 'Eva',
            original_title: 'Eva',
            overview:
              'When Eva gets involved in a steamy threesome with a houseboy and her lady boss, she realizes she has to choose only one between them.',
            poster_path: '/bXZ3j3kQgCRZj7KD4Q5F9m5ABaQ.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'tl',
            genre_ids: [18, 10749],
            popularity: 42.637,
            release_date: '2021-12-24',
            video: false,
            vote_average: 5.2,
            vote_count: 13,
          },
          {
            backdrop_path: '/kGD5j5FpAOXKVuWkCpfDMlqKGbq.jpg',
            id: 1015333,
            title: 'The Escort Wife',
            original_title: 'The Escort Wife',
            overview:
              'A wife who just had a miscarriage finds out that her husband is having an affair with a high-end escort. She turns into prostitution and will take her revenge on her...',
            poster_path: '/9cAFsL9dMWrqbfNMomSkkLBJsBS.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'tl',
            genre_ids: [53],
            popularity: 27.579,
            release_date: '2022-09-16',
            video: false,
            vote_average: 4.571,
            vote_count: 7,
          },
          {
            backdrop_path: '/1SJZxBUM1woyTK2yTFK4nHvh4C.jpg',
            id: 1091393,
            title: 'Domme',
            original_title: 'Domme',
            overview:
              'A man spies on his neighbors because of the noises they create every night. But he discovers that they do wild erotic practices. As he interferes with their business, the more he gets involved in their lives and their mess.',
            poster_path: '/yBScz1TeUs55fDKKUl4OvvZlO67.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'tl',
            genre_ids: [18],
            popularity: 11.054,
            release_date: '2023-03-17',
            video: false,
            vote_average: 4.5,
            vote_count: 4,
          },
        ],
      },
      {
        adult: false,
        gender: 1,
        id: 10882,
        known_for_department: 'Acting',
        name: 'Rosamund Pike',
        original_name: 'Rosamund Pike',
        popularity: 126.075,
        profile_path: '/8ObNklHDi2hjdz0ayzJFB9jtqzm.jpg',
        known_for: [
          {
            backdrop_path: '/h2JaQWLKhapm7AuSViJwGiv8ngC.jpg',
            id: 210577,
            title: 'Gone Girl',
            original_title: 'Gone Girl',
            overview:
              "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.",
            poster_path: '/lv5xShBIDPe7m4ufdlV0IAc7Avk.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [9648, 53, 18],
            popularity: 123.557,
            release_date: '2014-10-01',
            video: false,
            vote_average: 7.893,
            vote_count: 18256,
          },
          {
            backdrop_path: '/iwvP8XVpYVmJ3xfF9xdBi5uAOWl.jpg',
            id: 75780,
            title: 'Jack Reacher',
            original_title: 'Jack Reacher',
            overview:
              "One morning in an ordinary town, five people are shot dead in a seemingly random attack. All evidence points to a single suspect: an ex-military sniper who is quickly brought into custody. The interrogation yields one written note: 'Get Jack Reacher!'. Reacher, an enigmatic ex-Army investigator, believes the authorities have the right man but agrees to help the sniper's defense attorney. However, the more Reacher delves into the case, the less clear-cut it appears. So begins an extraordinary chase for the truth, pitting Jack Reacher against an unexpected enemy, with a skill for violence and a secret to keep.",
            poster_path: '/uQBbjrLVsUibWxNDGA4Czzo8lwz.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [80, 18, 53, 28],
            popularity: 51.335,
            release_date: '2012-12-20',
            video: false,
            vote_average: 6.627,
            vote_count: 6845,
          },
          {
            backdrop_path: '/nuZMOvban3QbG4rRx0WRfEZTnfh.jpg',
            id: 601666,
            title: 'I Care a Lot',
            original_title: 'I Care a Lot',
            overview:
              'A court-appointed legal guardian defrauds her older clients and traps them under her care. But her latest mark comes with some unexpected baggage.',
            poster_path: '/gKnhEsjNefpKnUdAkn7INzIFLSu.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [35, 80, 53, 18],
            popularity: 29.46,
            release_date: '2021-02-19',
            video: false,
            vote_average: 6.609,
            vote_count: 2589,
          },
        ],
      },
    ],
    movies: [
      {
        backdrop_path: '/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg',
        id: 1048241,
        title: 'My Spy the Eternal City',
        original_title: 'My Spy the Eternal City',
        overview:
          'JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.',
        poster_path: '/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [28, 35],
        popularity: 274.59,
        release_date: '2024-07-18',
        video: false,
        vote_average: 7.045,
        vote_count: 66,
      },
      {
        backdrop_path: '/fpo2qM5b4gTF5EHuYGlxsDIlZOj.jpg',
        id: 774531,
        title: 'Young Woman and the Sea',
        original_title: 'Young Woman and the Sea',
        overview:
          'The True Story of a young Trudy Ederle, who fights to overcome adversity and the animosity of a patriarchal society to rise through the ranks of the Olympic swimming team. Against all odds, she sets her sights on completing a staggering and dangerous journey — to become the first woman to swim across the brutal 21-mile stretch known as The English Channel.',
        poster_path: '/bZlecCuBVvKuarNGvchBwaOsQ3c.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [36, 18],
        popularity: 49.342,
        release_date: '2024-05-31',
        video: false,
        vote_average: 7.641,
        vote_count: 46,
      },
      {
        backdrop_path: '/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg',
        id: 718821,
        title: 'Twisters',
        original_title: 'Twisters',
        overview:
          'As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.',
        poster_path: '/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [28, 12, 53],
        popularity: 771.648,
        release_date: '2024-07-10',
        video: false,
        vote_average: 7.386,
        vote_count: 132,
      },
      {
        backdrop_path: '/peE1ax04MnTQ9ChDryoDNF95r5.jpg',
        id: 1255350,
        title: 'Find Me Falling',
        original_title: 'Find Me Falling',
        overview:
          'After a failed comeback album, rock star John Allman escapes to a dreamy Mediterranean island, only to discover that his new cliffside home has an unfortunate notoriety that attracts unwanted visitors and an old flame.',
        poster_path: '/pMWpIPJgL4lYNKxSVMRDFWITeMW.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [10749, 35, 10402],
        popularity: 106.83,
        release_date: '2024-07-19',
        video: false,
        vote_average: 6,
        vote_count: 11,
      },
      {
        backdrop_path: '/9l1eZiJHmhr5jIlthMdJN5WYoff.jpg',
        id: 533535,
        title: 'Deadpool & Wolverine',
        original_title: 'Deadpool & Wolverine',
        overview:
          'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
        poster_path: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [878, 28, 35],
        popularity: 849.864,
        release_date: '2024-07-24',
        video: false,
        vote_average: 8.5,
        vote_count: 10,
      },
      {
        backdrop_path: '/wkPPRIducGfsbaUPsWfw0MCQdX7.jpg',
        id: 1051891,
        title: 'Thelma',
        original_title: 'Thelma',
        overview:
          'When 93-year-old Thelma Post gets duped by a phone scammer pretending to be her grandson, she sets out on a treacherous quest across the city to reclaim what was taken from her.',
        poster_path: '/rUcuageYgv9SsJoWuc0seRWG6JC.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [28, 35, 12],
        popularity: 46.644,
        release_date: '2024-06-21',
        video: false,
        vote_average: 7.8,
        vote_count: 17,
      },
      {
        backdrop_path: '/fqv8v6AycXKsivp1T5yKtLbGXce.jpg',
        id: 653346,
        title: 'Kingdom of the Planet of the Apes',
        original_title: 'Kingdom of the Planet of the Apes',
        overview:
          "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
        poster_path: '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [878, 12, 28],
        popularity: 1631,
        release_date: '2024-05-08',
        video: false,
        vote_average: 7.138,
        vote_count: 1966,
      },
      {
        backdrop_path: '/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg',
        id: 1022789,
        title: 'Inside Out 2',
        original_title: 'Inside Out 2',
        overview:
          "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
        poster_path: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [16, 10751, 12, 35],
        popularity: 5571.077,
        release_date: '2024-06-11',
        video: false,
        vote_average: 7.683,
        vote_count: 1943,
      },
      {
        backdrop_path: '/dsGwCEO8tda4FlgHKvL95f0oQbH.jpg',
        id: 1209290,
        title: 'Justice League: Crisis on Infinite Earths Part Three',
        original_title: 'Justice League: Crisis on Infinite Earths Part Three',
        overview:
          'Now fully revealed as the ultimate threat to existence, the Anti-Monitor wages an unrelenting attack on the surviving Earths that struggle for survival in a pocket universe. One by one, these worlds and all their inhabitants are vaporized! On the planets that remain, even time itself is shattered, and heroes from the past join the Justice League and their rag-tag allies against the epitome of evil. But as they make their last stand, will the sacrifice of the superheroes be enough to save us all?',
        poster_path: '/a3q8NkM8uTh9E23VsbUOdDSbBeN.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [16, 878, 28],
        popularity: 439.054,
        release_date: '2024-07-16',
        video: false,
        vote_average: 7.406,
        vote_count: 53,
      },
      {
        backdrop_path: '/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg',
        id: 786892,
        title: 'Furiosa: A Mad Max Saga',
        original_title: 'Furiosa: A Mad Max Saga',
        overview:
          'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.',
        poster_path: '/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [28, 12, 878],
        popularity: 1872.179,
        release_date: '2024-05-22',
        video: false,
        vote_average: 7.65,
        vote_count: 2224,
      },
      {
        backdrop_path: '/8UOAYjhwSF3aPZhm6wgLuyHRyrR.jpg',
        id: 932086,
        title: 'Horizon: An American Saga - Chapter 1',
        original_title: 'Horizon: An American Saga - Chapter 1',
        overview:
          'Follow the story of how the Old West was won—and lost—through the blood, sweat and tears of many. Spanning 15 years before, during and following the Civil War from 1859 to 1874, embark on an emotional journey across a country at war with itself, experienced through the lens of families, friends and foes all attempting to discover what it truly means to be the United States of America.',
        poster_path: '/hqDkO0W9uk4aiwzn3pTeLO7NPZD.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [37, 18],
        popularity: 515.866,
        release_date: '2024-06-26',
        video: false,
        vote_average: 7.024,
        vote_count: 104,
      },
      {
        backdrop_path: '/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg',
        id: 519182,
        title: 'Despicable Me 4',
        original_title: 'Despicable Me 4',
        overview:
          'Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.',
        poster_path: '/3w84hCFJATpiCO5g8hpdWVPBbmq.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [16, 10751, 35, 28],
        popularity: 4439.3,
        release_date: '2024-06-20',
        video: false,
        vote_average: 7.381,
        vote_count: 340,
      },
      {
        backdrop_path: '/5Eip60UDiPLASyKjmHPMruggTc4.jpg',
        id: 1041613,
        title: 'Immaculate',
        original_title: 'Immaculate',
        overview:
          'An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.',
        poster_path: '/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [27, 9648, 53],
        popularity: 417.723,
        release_date: '2024-03-20',
        video: false,
        vote_average: 6.321,
        vote_count: 718,
      },
      {
        backdrop_path: '/a4IWRYNMNMszIkRbEIiNsRg6cvt.jpg',
        id: 929590,
        title: 'Civil War',
        original_title: 'Civil War',
        overview:
          'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.',
        poster_path: '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [10752, 28, 18],
        popularity: 793.972,
        release_date: '2024-04-10',
        video: false,
        vote_average: 6.988,
        vote_count: 1930,
      },
      {
        backdrop_path: '/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg',
        id: 974262,
        title: 'Descendants: The Rise of Red',
        original_title: 'Descendants: The Rise of Red',
        overview:
          "After the Queen of Hearts incites a coup on Auradon, her rebellious daughter Red and Cinderella's perfectionist daughter Chloe join forces and travel back in time to try to undo the traumatic event that set Red's mother down her villainous path.",
        poster_path: '/8fYluTtB3b3HKO7KQa5tzrvGaps.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [14, 12, 10751, 35],
        popularity: 2030.613,
        release_date: '2024-07-11',
        video: false,
        vote_average: 7.257,
        vote_count: 148,
      },
      {
        backdrop_path: '/Avtx5jsdPuDa091jvx2Lye3ygke.jpg',
        id: 1226578,
        title: 'Longlegs',
        original_title: 'Longlegs',
        overview:
          'In pursuit of a serial killer, an FBI agent uncovers a series of occult clues that she must solve to end his terrifying killing spree.',
        poster_path: '/dLAP1apgFIoBoPNw4HJLVACSu7u.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [80, 27, 53],
        popularity: 190.849,
        release_date: '2024-07-10',
        video: false,
        vote_average: 6.806,
        vote_count: 111,
      },
      {
        backdrop_path: '/60qVuzQOKgyD57tsgBceT5ScCSX.jpg',
        id: 1214488,
        title: 'Skywalkers: A Love Story',
        original_title: 'Skywalkers: A Love Story',
        overview:
          "Two real-life daredevils test the limits of their love and trust by illegally scaling one of the world's tallest buildings to perform an acrobatic stunt.",
        poster_path: '/7A4x0D1gNTpmMn9E9BW9hWiaOkv.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [99, 10749, 53],
        popularity: 28.489,
        release_date: '2024-07-12',
        video: false,
        vote_average: 7.9,
        vote_count: 15,
      },
      {
        backdrop_path: '/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg',
        id: 748783,
        title: 'The Garfield Movie',
        original_title: 'The Garfield Movie',
        overview:
          'Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.',
        poster_path: '/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [16, 35, 10751, 12],
        popularity: 2173.538,
        release_date: '2024-04-30',
        video: false,
        vote_average: 7.3,
        vote_count: 504,
      },
      {
        backdrop_path: '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
        id: 693134,
        title: 'Dune: Part Two',
        original_title: 'Dune: Part Two',
        overview:
          'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
        poster_path: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [878, 12],
        popularity: 382.953,
        release_date: '2024-02-27',
        video: false,
        vote_average: 8.166,
        vote_count: 4867,
      },
      {
        backdrop_path: '/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg',
        id: 7451,
        title: 'xXx',
        original_title: 'xXx',
        overview:
          'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
        poster_path: '/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [28, 12, 53, 80],
        popularity: 438.996,
        release_date: '2002-08-09',
        video: false,
        vote_average: 5.9,
        vote_count: 4120,
      },
    ],
    series: [
      {
        backdrop_path: '/7cqKGQMnNabzOpi7qaIgZvQ7NGV.jpg',
        id: 76479,
        name: 'The Boys',
        original_name: 'The Boys',
        overview:
          'A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.',
        poster_path: '/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [10765, 10759],
        popularity: 2947.075,
        first_air_date: '2019-07-25',
        vote_average: 8.5,
        vote_count: 9997,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/3m9t52rcLdQuDNEnyhtpn9y9CGp.jpg',
        id: 218589,
        name: 'Those About to Die',
        original_name: 'Those About to Die',
        overview:
          'Within the spectacular, complex and corrupt world of gladiatorial sports in Ancient Rome, follow an ensemble of diverse characters across the many layers of Roman society where sports, politics and business intersect and collide.',
        poster_path: '/gvz0m4MJ8sAj6yMcQdwN07bNjRY.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [18],
        popularity: 288.757,
        first_air_date: '2024-07-18',
        vote_average: 8.2,
        vote_count: 12,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/mceCXNTny6a5F3rQgShLoyARw4l.jpg',
        id: 96648,
        name: 'Sweet Home',
        original_name: '스위트홈',
        overview:
          'As humans turn into savage monsters and the world plunges into terror, a handful of survivors fight for their lives — and to hold on to their humanity.',
        poster_path: '/7wbPHetLZnyL6hwqrfEPnLNKnXu.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ko',
        genre_ids: [18, 10765, 80],
        popularity: 907.785,
        first_air_date: '2020-12-18',
        vote_average: 8.3,
        vote_count: 1274,
        origin_country: ['KR'],
      },
      {
        backdrop_path: '/xFJS2FeCfCztFWO9yEW0RV2uFz.jpg',
        id: 77169,
        name: 'Cobra Kai',
        original_name: 'Cobra Kai',
        overview:
          'This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.',
        poster_path: '/6GDW4EsgsXlYrL1ASb5eCHQK4er.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [10759, 18, 35],
        popularity: 2584.134,
        first_air_date: '2018-05-02',
        vote_average: 8.216,
        vote_count: 6029,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/iYQlpBH9RHmoDVcvGsvNpG3Ikx5.jpg',
        id: 120549,
        name: 'Lady in the Lake',
        original_name: 'Lady in the Lake',
        overview:
          'When the disappearance of a young girl grips the city of Baltimore in 1966, the lives of two women converge on a fatal collision course.',
        poster_path: '/cK0zAfFHfpSZJ5e9yhm2jRJJ6Zj.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [18, 80],
        popularity: 140.435,
        first_air_date: '2024-07-18',
        vote_average: 7.5,
        vote_count: 8,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/kwronSXO1ogMqHHFvY2eBxfFLdn.jpg',
        id: 114479,
        name: 'The Acolyte',
        original_name: 'The Acolyte',
        overview:
          'A hundred years before the rise of the Empire, the Jedi Order and the Galactic Republic have prospered for centuries without war. During this time, an investigation into a shocking crime spree pits a Jedi Master against a dangerous warrior from his past.',
        poster_path: '/fW2nOB5EXEOh64qufAxeW4AU3AB.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [9648, 10765],
        popularity: 572.82,
        first_air_date: '2024-06-04',
        vote_average: 5.7,
        vote_count: 350,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/ueVgPm1VN6ZgEtzj9WUOpSMj4d0.jpg',
        id: 258759,
        name: 'Strange Tales of Tang Dynasty II To the West',
        original_name: '唐朝诡事录之西行',
        overview: '',
        poster_path: '/usptf7Hj21E34GsIOycKJjV4Arg.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'zh',
        genre_ids: [9648],
        popularity: 56.703,
        first_air_date: '2024-07-18',
        vote_average: 6,
        vote_count: 1,
        origin_country: ['CN'],
      },
      {
        backdrop_path: '/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg',
        id: 94997,
        name: 'House of the Dragon',
        original_name: 'House of the Dragon',
        overview:
          'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.',
        poster_path: '/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [10765, 18, 10759],
        popularity: 3277.952,
        first_air_date: '2022-08-21',
        vote_average: 8.417,
        vote_count: 4446,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/m2D5bhoAB0ewe42m8rfIl0a1ahM.jpg',
        id: 211089,
        name: 'Strange Tales Of Tang Dynasty',
        original_name: '唐朝诡事录',
        overview:
          "When the dark evil immortal descends from the heaven, and the mysterious underground ghost palace was revealed, a strange herb named the Black Tea suddenly took Chang'an City by storm. However, no one knows whether it is a healthy medicine or one that could harm people. Cases of missing brides in Chang'an City began occurring one after another, which seems to be inextricably linked to the black tea...  Ling Feng, general of the Jin Wu guards was tasked to investigate these cases. On his journey, he meets his strongest opponent in Su Wu Ming, the disciple of Di Ren Jie. The two of them work together to solve these mysterious cases.",
        poster_path: '/y8a0sXfO1tn5KGH6mRVn7FnPdkW.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'zh',
        genre_ids: [9648, 80, 10759],
        popularity: 427.673,
        first_air_date: '2022-09-27',
        vote_average: 8.2,
        vote_count: 13,
        origin_country: ['CN'],
      },
      {
        backdrop_path: '/us2E4vqo5zJrUledrNX1KTpk3gT.jpg',
        id: 230424,
        name: 'Betty la Fea, the Story Continues',
        original_name: 'Betty la fea, la historia continúa',
        overview:
          'While an empowered and wiser Betty works hard on rebuilding her relationship with her teenage daughter Mila, her relationship with Armando begins to deteriorate, making her question if she made the right decision 20 years ago.',
        poster_path: '/sgCcmsJ4aKAK8QwrbG6RLYxxFAj.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'es',
        genre_ids: [10766, 35],
        popularity: 362.526,
        first_air_date: '2024-07-19',
        vote_average: 8.429,
        vote_count: 28,
        origin_country: ['CO'],
      },
      {
        backdrop_path: '/2WBO3C7CjsOTT5wgi9Inn5iQhVv.jpg',
        id: 46195,
        name: 'Monogatari',
        original_name: '化物語',
        overview:
          'Although there are still traces of the brief period he became a vampire, third-year high school student Koyomi Araragi is human again. He happens upon others with their own supernatural problems and finds that he can empathize. Koyomi becomes involved in their lives, seeking to help them and occasionally asking for advice from Meme Oshino, the homeless man who helped him become human again.',
        poster_path: '/zCEjjb1NH3LLsWeZx47wOeqkezf.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ja',
        genre_ids: [16, 35, 18, 9648],
        popularity: 434.77,
        first_air_date: '2009-07-03',
        vote_average: 8.133,
        vote_count: 446,
        origin_country: ['JP'],
      },
      {
        backdrop_path: '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
        id: 37854,
        name: 'One Piece',
        original_name: 'ワンピース',
        overview:
          'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
        poster_path: '/e3NBGiAifW9Xt8xD5tpARskjccO.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ja',
        genre_ids: [10759, 35, 16],
        popularity: 146.921,
        first_air_date: '1999-10-20',
        vote_average: 8.721,
        vote_count: 4525,
        origin_country: ['JP'],
      },
      {
        backdrop_path: '/wHNwlE6ftEpgjVbdhLXOtv1hLs0.jpg',
        id: 136315,
        name: 'The Bear',
        original_name: 'The Bear',
        overview:
          'Carmy, a young fine-dining chef, comes home to Chicago to run his family sandwich shop. As he fights to transform the shop and himself, he works alongside a rough-around-the-edges crew that ultimately reveal themselves as his chosen family.',
        poster_path: '/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [18, 35],
        popularity: 444.281,
        first_air_date: '2022-06-23',
        vote_average: 8.289,
        vote_count: 966,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/l31qDy1jqKcoXmCkcAvDrqebwkX.jpg',
        id: 250850,
        name: 'Master of the House',
        original_name: 'สืบสันดาน',
        overview:
          'A family enters a power struggle following the death of their patriarch, who leaves behind his diamond empire — and the housekeeper he recently married.',
        poster_path: '/bJnrzJWTFXUN64EUiFzHCMj9SfW.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'th',
        genre_ids: [18, 9648],
        popularity: 264.496,
        first_air_date: '2024-07-18',
        vote_average: 7.75,
        vote_count: 4,
        origin_country: ['TH'],
      },
      {
        backdrop_path: '/vfE3gd2VoWbJ2h5E1IOialJawgv.jpg',
        id: 70722,
        name: 'Momokyun Sword',
        original_name: 'モモキュンソード',
        overview:
          "Momoko is a beautiful young sword fighter who was born inside a peach. She lives with her constant companions—the dog god Inugami, the monkey god Sarugami, and the pheasant god Kijigami—in a peaceful paradise. However, a demon army led by devil king invades the paradise and steals the precious treasure that protects Momoko's land. To retrieve the treasure and save the people, Momoko embarks on a great adventure with her three companions.",
        poster_path: '/tg6HZ5SKGv7ezXxjwXn24MHYlnr.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ja',
        genre_ids: [10759, 16],
        popularity: 57.018,
        first_air_date: '2014-07-09',
        vote_average: 7.1,
        vote_count: 11,
        origin_country: ['JP'],
      },
      {
        backdrop_path: '/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg',
        id: 1399,
        name: 'Game of Thrones',
        original_name: 'Game of Thrones',
        overview:
          "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
        poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [10765, 18, 10759],
        popularity: 1908.623,
        first_air_date: '2011-04-17',
        vote_average: 8.453,
        vote_count: 23464,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/peENvis00Fkw27KLFuaoWsu0YnD.jpg',
        id: 79680,
        name: 'Snowpiercer',
        original_name: 'Snowpiercer',
        overview:
          'More than seven years after the world has become a frozen wasteland, the remnants of humanity inhabit a gigantic, perpetually-moving train that circles the globe as class warfare, social injustice and the politics of survival play out.',
        poster_path: '/exKzfiKzMdQBHrdd7zNmKauJkbg.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [10765],
        popularity: 472.387,
        first_air_date: '2020-05-17',
        vote_average: 7.4,
        vote_count: 1169,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/gArCVC4ML529WMCEqOXbALdQbUq.jpg',
        id: 203737,
        name: 'Oshi No Ko',
        original_name: '【推しの子】',
        overview:
          'Dr. Goro is reborn as the son of the young starlet Ai Hoshino after her delusional stalker murders him. Now, he wants to help his new mother rise to the top, but what can a child do about the dark underbelly of the entertainment industry?',
        poster_path: '/rFp74PFpz14AHrtlVPrLyrSng47.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ja',
        genre_ids: [16, 18],
        popularity: 317.033,
        first_air_date: '2023-04-12',
        vote_average: 8.278,
        vote_count: 171,
        origin_country: ['JP'],
      },
      {
        backdrop_path: '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
        id: 1429,
        name: 'Attack on Titan',
        original_name: '進撃の巨人',
        overview:
          'Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.',
        poster_path: '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ja',
        genre_ids: [16, 10765, 10759],
        popularity: 150.795,
        first_air_date: '2013-04-07',
        vote_average: 8.661,
        vote_count: 6174,
        origin_country: ['JP'],
      },
      {
        backdrop_path: '/qzi8rTS2KpkrYNWxC1tt7xkRlTY.jpg',
        id: 156933,
        name: 'Presumed Innocent',
        original_name: 'Presumed Innocent',
        overview:
          "A horrific murder upends the Chicago Prosecuting Attorney's Office when one of its own is suspected of the crime—leaving the accused fighting to keep his family together.",
        poster_path: '/7MXg0BxuSRWz2yKc03M40du2mrc.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [18, 9648],
        popularity: 606.997,
        first_air_date: '2024-06-11',
        vote_average: 8.158,
        vote_count: 114,
        origin_country: ['US'],
      },
    ],
  };

  protected headerButtons: HeaderButton[] = [
    {
      type: 'icon',
      iconPath: '../../../../assets/icons/home-header/Github-solid.svg',
      anchor: {
        urlType: 'external',
        path: 'https://github.com/Scottify20/salida',
        target: '_blank',
      },
    },
    {
      type: 'text',
      text: 'Logo',
      anchor: {
        urlType: 'internal',
        path: '/',
        target: '_self',
      },
    },
    {
      type: 'icon',
      iconPath: '../../../../assets/icons/home-header/User-solid.svg',
      anchor: {
        urlType: 'internal',
        path: '/user',
        target: '_self',
      },
    },
  ];

  protected movies: TmdbEntityForCard[] = this.tmdbEntities.movies.map(
    (movie) => ({
      name: movie.title,
      image_path: movie.poster_path,
    })
  );
  protected series: TmdbEntityForCard[] = this.tmdbEntities.series.map(
    (series) => ({
      name: series.name,
      image_path: series.poster_path,
    })
  );

  protected persons: TmdbEntityForCard[] = this.tmdbEntities.persons.map(
    (person) => ({
      name: person.name,
      image_path: person.profile_path,
    })
  );

  @ViewChild(HeroCardsComponent) heroCards!: HeroCardsComponent;

  ngAfterViewInit() {
    this.heroCards.startCardsScrollBasedAnimation();
  }
  ngOnDestroy() {
    this.heroCards.stopCardsScrollBasedAnimation();
  }

  trendingMoviesOptions: CardsSectionOptions = {
    sectionTitle: 'Movies',
    entities: this.movies,
    maxNoOfCards: 20,
    buttonProps: {
      type: 'text',
      textOrIconPath: 'See all',
      callback: this.sampleCallback,
    },
  };

  trendingSeriesOptions: CardsSectionOptions = {
    sectionTitle: 'TV Series',
    maxNoOfCards: 20,
    entities: this.series,
    buttonProps: {
      type: 'text',
      textOrIconPath: 'See all',
      callback: this.sampleCallback,
    },
  };

  trendingPeopleOptions: CardsSectionOptions = {
    sectionTitle: 'People',
    entities: this.persons,
    maxNoOfCards: 20,
    buttonProps: {
      type: 'text',
      textOrIconPath: 'See all',
      callback: this.sampleCallback,
    },
    cardShape: 'circle',
  };

  sampleCallback() {}
}
