import { AfterViewInit, Component, OnDestroy, ViewChild } from '@angular/core';

import { HeroCardsComponent } from './hero-cards/hero-cards.component';
import { ButtonsHeaderComponent } from '../shared/components/buttons-header/buttons-header.component';
import { TitlesCardsSectionComponent } from '../shared/components/titles-cards-section/titles-cards-section.component';

@Component({
  selector: 'app-home',
  standalone: true,
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
  imports: [
    ButtonsHeaderComponent,
    HeroCardsComponent,
    TitlesCardsSectionComponent,
  ],
})
export class HomeComponent implements AfterViewInit, OnDestroy {
  movies: Movie[] = [
    {
      backdrop_path: '/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg',
      id: 1048241,
      title: 'My Spy the Eternal City',
      original_title: 'My Spy the Eternal City',
      overview:
        'JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.',
      poster_path: '/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 35],
      popularity: 196.136,
      release_date: '2024-07-18',
      video: false,
      vote_average: 7.1,
      vote_count: 46,
    },
    {
      backdrop_path: '/fpo2qM5b4gTF5EHuYGlxsDIlZOj.jpg',
      id: 774531,
      title: 'Young Woman and the Sea',
      original_title: 'Young Woman and the Sea',
      overview:
        'The True Story of a young Trudy Ederle, who fights to overcome adversity and the animosity of a patriarchal society to rise through the ranks of the Olympic swimming team. Against all odds, she sets her sights on completing a staggering and dangerous journey — to become the first woman to swim across the brutal 21-mile stretch known as The English Channel.',
      poster_path: '/bZlecCuBVvKuarNGvchBwaOsQ3c.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [36, 18],
      popularity: 35.244,
      release_date: '2024-05-31',
      video: false,
      vote_average: 7.4,
      vote_count: 25,
    },
    {
      backdrop_path: '/peE1ax04MnTQ9ChDryoDNF95r5.jpg',
      id: 1255350,
      title: 'Find Me Falling',
      original_title: 'Find Me Falling',
      overview:
        'After a failed comeback album, rock star John Allman escapes to a dreamy Mediterranean island, only to discover that his new cliffside home has an unfortunate notoriety that attracts unwanted visitors and an old flame.',
      poster_path: '/pMWpIPJgL4lYNKxSVMRDFWITeMW.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [10749, 35, 10402],
      popularity: 76.307,
      release_date: '2024-07-19',
      video: false,
      vote_average: 6,
      vote_count: 3,
    },
    {
      backdrop_path: '/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg',
      id: 718821,
      title: 'Twisters',
      original_title: 'Twisters',
      overview:
        'As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.',
      poster_path: '/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 12, 53],
      popularity: 643.96,
      release_date: '2024-07-10',
      video: false,
      vote_average: 7.481,
      vote_count: 108,
    },
    {
      backdrop_path: '/dvBCdCohwWbsP5qAaglOXagDMtk.jpg',
      id: 533535,
      title: 'Deadpool & Wolverine',
      original_title: 'Deadpool & Wolverine',
      overview:
        'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
      poster_path: '/jbwYaoYWZwxtPP76AZnfYKQjCEB.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [878, 28, 35],
      popularity: 748.36,
      release_date: '2024-07-24',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: '/wkPPRIducGfsbaUPsWfw0MCQdX7.jpg',
      id: 1051891,
      title: 'Thelma',
      original_title: 'Thelma',
      overview:
        'When 93-year-old Thelma Post gets duped by a phone scammer pretending to be her grandson, she sets out on a treacherous quest across the city to reclaim what was taken from her.',
      poster_path: '/rUcuageYgv9SsJoWuc0seRWG6JC.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 35, 12],
      popularity: 33.317,
      release_date: '2024-06-21',
      video: false,
      vote_average: 7.4,
      vote_count: 12,
    },
    {
      backdrop_path: '/fqv8v6AycXKsivp1T5yKtLbGXce.jpg',
      id: 653346,
      title: 'Kingdom of the Planet of the Apes',
      original_title: 'Kingdom of the Planet of the Apes',
      overview:
        "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
      poster_path: '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [878, 12, 28],
      popularity: 1526.548,
      release_date: '2024-05-08',
      video: false,
      vote_average: 7.136,
      vote_count: 1943,
    },
    {
      backdrop_path: '/dsGwCEO8tda4FlgHKvL95f0oQbH.jpg',
      id: 1209290,
      title: 'Justice League: Crisis on Infinite Earths Part Three',
      original_title: 'Justice League: Crisis on Infinite Earths Part Three',
      overview:
        'Now fully revealed as the ultimate threat to existence, the Anti-Monitor wages an unrelenting attack on the surviving Earths that struggle for survival in a pocket universe. One by one, these worlds and all their inhabitants are vaporized! On the planets that remain, even time itself is shattered, and heroes from the past join the Justice League and their rag-tag allies against the epitome of evil. But as they make their last stand, will the sacrifice of the superheroes be enough to save us all?',
      poster_path: '/a3q8NkM8uTh9E23VsbUOdDSbBeN.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [16, 878, 28],
      popularity: 313.61,
      release_date: '2024-07-16',
      video: false,
      vote_average: 7.567,
      vote_count: 45,
    },
    {
      backdrop_path: '/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg',
      id: 1022789,
      title: 'Inside Out 2',
      original_title: 'Inside Out 2',
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      poster_path: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [16, 10751, 12, 35],
      popularity: 5100.537,
      release_date: '2024-06-11',
      video: false,
      vote_average: 7.685,
      vote_count: 1925,
    },
    {
      backdrop_path: '/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg',
      id: 974262,
      title: 'Descendants: The Rise of Red',
      original_title: 'Descendants: The Rise of Red',
      overview:
        "After the Queen of Hearts incites a coup on Auradon, her rebellious daughter Red and Cinderella's perfectionist daughter Chloe join forces and travel back in time to try to undo the traumatic event that set Red's mother down her villainous path.",
      poster_path: '/8fYluTtB3b3HKO7KQa5tzrvGaps.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [14, 12, 10751, 35],
      popularity: 2015.902,
      release_date: '2024-07-11',
      video: false,
      vote_average: 7.3,
      vote_count: 145,
    },
    {
      backdrop_path: '/8UOAYjhwSF3aPZhm6wgLuyHRyrR.jpg',
      id: 932086,
      title: 'Horizon: An American Saga - Chapter 1',
      original_title: 'Horizon: An American Saga - Chapter 1',
      overview:
        'Follow the story of how the Old West was won—and lost—through the blood, sweat and tears of many. Spanning 15 years before, during and following the Civil War from 1859 to 1874, embark on an emotional journey across a country at war with itself, experienced through the lens of families, friends and foes all attempting to discover what it truly means to be the United States of America.',
      poster_path: '/hqDkO0W9uk4aiwzn3pTeLO7NPZD.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [37, 18],
      popularity: 405.481,
      release_date: '2024-06-26',
      video: false,
      vote_average: 7.1,
      vote_count: 100,
    },
    {
      backdrop_path: '/5Eip60UDiPLASyKjmHPMruggTc4.jpg',
      id: 1041613,
      title: 'Immaculate',
      original_title: 'Immaculate',
      overview:
        'An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.',
      poster_path: '/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [27, 9648, 53],
      popularity: 373.756,
      release_date: '2024-03-20',
      video: false,
      vote_average: 6.321,
      vote_count: 709,
    },
    {
      backdrop_path: '/Avtx5jsdPuDa091jvx2Lye3ygke.jpg',
      id: 1226578,
      title: 'Longlegs',
      original_title: 'Longlegs',
      overview:
        'In pursuit of a serial killer, an FBI agent uncovers a series of occult clues that she must solve to end his terrifying killing spree.',
      poster_path: '/dLAP1apgFIoBoPNw4HJLVACSu7u.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [80, 27, 53],
      popularity: 216.978,
      release_date: '2024-07-10',
      video: false,
      vote_average: 6.766,
      vote_count: 107,
    },
    {
      backdrop_path: '/a4IWRYNMNMszIkRbEIiNsRg6cvt.jpg',
      id: 929590,
      title: 'Civil War',
      original_title: 'Civil War',
      overview:
        'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.',
      poster_path: '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [10752, 28, 18],
      popularity: 713.519,
      release_date: '2024-04-10',
      video: false,
      vote_average: 6.99,
      vote_count: 1922,
    },
    {
      backdrop_path: '/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg',
      id: 519182,
      title: 'Despicable Me 4',
      original_title: 'Despicable Me 4',
      overview:
        'Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.',
      poster_path: '/3w84hCFJATpiCO5g8hpdWVPBbmq.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [16, 10751, 35, 28],
      popularity: 3949.4,
      release_date: '2024-06-20',
      video: false,
      vote_average: 7.4,
      vote_count: 328,
    },
    {
      backdrop_path: '/60qVuzQOKgyD57tsgBceT5ScCSX.jpg',
      id: 1214488,
      title: 'Skywalkers: A Love Story',
      original_title: 'Skywalkers: A Love Story',
      overview:
        "Two real-life daredevils test the limits of their love and trust by illegally scaling one of the world's tallest buildings to perform an acrobatic stunt.",
      poster_path: '/7A4x0D1gNTpmMn9E9BW9hWiaOkv.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [99, 10749, 53],
      popularity: 20.349,
      release_date: '2024-07-12',
      video: false,
      vote_average: 7.682,
      vote_count: 11,
    },
    {
      backdrop_path: '/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg',
      id: 786892,
      title: 'Furiosa: A Mad Max Saga',
      original_title: 'Furiosa: A Mad Max Saga',
      overview:
        'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.',
      poster_path: '/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [28, 12, 878],
      popularity: 1792.329,
      release_date: '2024-05-22',
      video: false,
      vote_average: 7.643,
      vote_count: 2207,
    },
    {
      backdrop_path: '/4xIBM8RwIvpwMlJSoF6tqFOaB6N.jpg',
      id: 592834,
      title: 'My Spy',
      original_title: 'My Spy',
      overview:
        'A hardened CIA operative finds himself at the mercy of a precocious 9-year-old girl, having been sent undercover to surveil her family.',
      poster_path: '/n2C6jRK9PtPIs99RQhKtqGlsnsO.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [10751, 28, 35],
      popularity: 100.15,
      release_date: '2020-01-09',
      video: false,
      vote_average: 6.876,
      vote_count: 1118,
    },
    {
      backdrop_path: '/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg',
      id: 748783,
      title: 'The Garfield Movie',
      original_title: 'The Garfield Movie',
      overview:
        'Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.',
      poster_path: '/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [16, 35, 10751, 12],
      popularity: 2053.649,
      release_date: '2024-04-30',
      video: false,
      vote_average: 7.27,
      vote_count: 489,
    },
    {
      backdrop_path: '/oMiKHO3H5RixfLsiU5Vumhlp5sj.jpg',
      id: 948549,
      title: 'Love Lies Bleeding',
      original_title: 'Love Lies Bleeding',
      overview:
        'Reclusive gym manager Lou falls hard for Jackie, an ambitious bodybuilder headed through town to Las Vegas in pursuit of her dream. But their love ignites violence, pulling them deep into the web of Lou’s criminal family.',
      poster_path: '/p7jyFWiLyHPttqYBFAlLJwtYTYH.jpg',
      media_type: 'movie',
      adult: false,
      original_language: 'en',
      genre_ids: [80, 10749, 53],
      popularity: 252.126,
      release_date: '2024-03-08',
      video: false,
      vote_average: 6.555,
      vote_count: 329,
    },
  ];

  series: Series[] = [
    {
      backdrop_path: '/7cqKGQMnNabzOpi7qaIgZvQ7NGV.jpg',
      id: 76479,
      name: 'The Boys',
      original_name: 'The Boys',
      overview:
        'A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.',
      poster_path: '/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [10765, 10759],
      popularity: 3784.897,
      first_air_date: '2019-07-25',
      vote_average: 8.5,
      vote_count: 9986,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/mceCXNTny6a5F3rQgShLoyARw4l.jpg',
      id: 96648,
      name: 'Sweet Home',
      original_name: '스위트홈',
      overview:
        'As humans turn into savage monsters and the world plunges into terror, a handful of survivors fight for their lives — and to hold on to their humanity.',
      poster_path: '/7wbPHetLZnyL6hwqrfEPnLNKnXu.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ko',
      genre_ids: [18, 10765, 80],
      popularity: 648.418,
      first_air_date: '2020-12-18',
      vote_average: 8.343,
      vote_count: 1270,
      origin_country: ['KR'],
    },
    {
      backdrop_path: '/vX71TGviqLsOtDNJ9q1QR4m14kH.jpg',
      id: 218589,
      name: 'Those About to Die',
      original_name: 'Those About to Die',
      overview:
        'Within the spectacular, complex and corrupt world of gladiatorial sports in Ancient Rome, follow an ensemble of diverse characters across the many layers of Roman society where sports, politics and business intersect and collide.',
      poster_path: '/gvz0m4MJ8sAj6yMcQdwN07bNjRY.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18],
      popularity: 206.255,
      first_air_date: '2024-07-18',
      vote_average: 9.1,
      vote_count: 8,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/zymbuoBoL1i94xAOzVJF6IuWLfD.jpg',
      id: 77169,
      name: 'Cobra Kai',
      original_name: 'Cobra Kai',
      overview:
        'This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.',
      poster_path: '/6GDW4EsgsXlYrL1ASb5eCHQK4er.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [10759, 18, 35],
      popularity: 1858.399,
      first_air_date: '2018-05-02',
      vote_average: 8.2,
      vote_count: 6026,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/iYQlpBH9RHmoDVcvGsvNpG3Ikx5.jpg',
      id: 120549,
      name: 'Lady in the Lake',
      original_name: 'Lady in the Lake',
      overview:
        'When the disappearance of a young girl grips the city of Baltimore in 1966, the lives of two women converge on a fatal collision course.',
      poster_path: '/cK0zAfFHfpSZJ5e9yhm2jRJJ6Zj.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 80],
      popularity: 100.311,
      first_air_date: '2024-07-18',
      vote_average: 8.167,
      vote_count: 6,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/kwronSXO1ogMqHHFvY2eBxfFLdn.jpg',
      id: 114479,
      name: 'The Acolyte',
      original_name: 'The Acolyte',
      overview:
        'A hundred years before the rise of the Empire, the Jedi Order and the Galactic Republic have prospered for centuries without war. During this time, an investigation into a shocking crime spree pits a Jedi Master against a dangerous warrior from his past.',
      poster_path: '/yuCKJsbzzadXh6tMUsIwZ2zaKXy.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [9648, 10765],
      popularity: 713.982,
      first_air_date: '2024-06-04',
      vote_average: 5.713,
      vote_count: 349,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/ueVgPm1VN6ZgEtzj9WUOpSMj4d0.jpg',
      id: 258759,
      name: 'Strange Tales of Tang Dynasty II To the West',
      original_name: '唐朝诡事录之西行',
      overview: '',
      poster_path: '/usptf7Hj21E34GsIOycKJjV4Arg.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'zh',
      genre_ids: [9648],
      popularity: 40.502,
      first_air_date: '2024-07-18',
      vote_average: 6,
      vote_count: 1,
      origin_country: ['CN'],
    },
    {
      backdrop_path: '/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg',
      id: 94997,
      name: 'House of the Dragon',
      original_name: 'House of the Dragon',
      overview:
        'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.',
      poster_path: '/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [10765, 18, 10759],
      popularity: 2341.394,
      first_air_date: '2022-08-21',
      vote_average: 8.417,
      vote_count: 4443,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/m2D5bhoAB0ewe42m8rfIl0a1ahM.jpg',
      id: 211089,
      name: 'Strange Tales Of Tang Dynasty',
      original_name: '唐朝诡事录',
      overview:
        "When the dark evil immortal descends from the heaven, and the mysterious underground ghost palace was revealed, a strange herb named the Black Tea suddenly took Chang'an City by storm. However, no one knows whether it is a healthy medicine or one that could harm people. Cases of missing brides in Chang'an City began occurring one after another, which seems to be inextricably linked to the black tea...  Ling Feng, general of the Jin Wu guards was tasked to investigate these cases. On his journey, he meets his strongest opponent in Su Wu Ming, the disciple of Di Ren Jie. The two of them work together to solve these mysterious cases.",
      poster_path: '/y8a0sXfO1tn5KGH6mRVn7FnPdkW.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'zh',
      genre_ids: [9648, 80, 10759],
      popularity: 305.481,
      first_air_date: '2022-09-27',
      vote_average: 8.2,
      vote_count: 13,
      origin_country: ['CN'],
    },
    {
      backdrop_path: '/us2E4vqo5zJrUledrNX1KTpk3gT.jpg',
      id: 230424,
      name: 'Betty la Fea, the Story Continues',
      original_name: 'Betty la fea, la historia continúa',
      overview:
        'While an empowered and wiser Betty works hard on rebuilding her relationship with her teenage daughter Mila, her relationship with Armando begins to deteriorate, making her question if she made the right decision 20 years ago.',
      poster_path: '/sgCcmsJ4aKAK8QwrbG6RLYxxFAj.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'es',
      genre_ids: [10766, 35],
      popularity: 258.947,
      first_air_date: '2024-07-19',
      vote_average: 8.4,
      vote_count: 15,
      origin_country: ['CO'],
    },
    {
      backdrop_path: '/l31qDy1jqKcoXmCkcAvDrqebwkX.jpg',
      id: 250850,
      name: 'Master of the House',
      original_name: 'สืบสันดาน',
      overview:
        'A family enters a power struggle following the death of their patriarch, who leaves behind his diamond empire — and the housekeeper he recently married.',
      poster_path: '/bJnrzJWTFXUN64EUiFzHCMj9SfW.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'th',
      genre_ids: [18, 9648],
      popularity: 188.926,
      first_air_date: '2024-07-18',
      vote_average: 7.75,
      vote_count: 4,
      origin_country: ['TH'],
    },
    {
      backdrop_path: '/gArCVC4ML529WMCEqOXbALdQbUq.jpg',
      id: 203737,
      name: 'Oshi No Ko',
      original_name: '【推しの子】',
      overview:
        'Dr. Goro is reborn as the son of the young starlet Ai Hoshino after her delusional stalker murders him. Now, he wants to help his new mother rise to the top, but what can a child do about the dark underbelly of the entertainment industry?',
      poster_path: '/rFp74PFpz14AHrtlVPrLyrSng47.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [16, 18],
      popularity: 490.641,
      first_air_date: '2023-04-12',
      vote_average: 8.278,
      vote_count: 171,
      origin_country: ['JP'],
    },
    {
      backdrop_path: '/wHNwlE6ftEpgjVbdhLXOtv1hLs0.jpg',
      id: 136315,
      name: 'The Bear',
      original_name: 'The Bear',
      overview:
        'Carmy, a young fine-dining chef, comes home to Chicago to run his family sandwich shop. As he fights to transform the shop and himself, he works alongside a rough-around-the-edges crew that ultimately reveal themselves as his chosen family.',
      poster_path: '/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 35],
      popularity: 456.572,
      first_air_date: '2022-06-23',
      vote_average: 8.3,
      vote_count: 964,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
      id: 37854,
      name: 'One Piece',
      original_name: 'ワンピース',
      overview:
        'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
      poster_path: '/e3NBGiAifW9Xt8xD5tpARskjccO.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [10759, 35, 16],
      popularity: 185.797,
      first_air_date: '1999-10-20',
      vote_average: 8.722,
      vote_count: 4524,
      origin_country: ['JP'],
    },
    {
      backdrop_path: '/tx1SyRqFxSC7aI0MJ5ZbPkpVd0v.jpg',
      id: 200753,
      name: 'Kite Man: Hell Yeah!',
      original_name: 'Kite Man: Hell Yeah!',
      overview:
        'Lovable loser Kite Man and his new squeeze Golden Glider moonlight as criminals to support their foolish purchase of Noonan’s, Gotham’s seediest dive bar, where everybody knows your name, but not necessarily your secret identity!',
      poster_path: '/cebce4aQiO4gRLiILxoZbzWUoEJ.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [16, 35],
      popularity: 128.568,
      first_air_date: '2024-07-18',
      vote_average: 8,
      vote_count: 3,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/peENvis00Fkw27KLFuaoWsu0YnD.jpg',
      id: 79680,
      name: 'Snowpiercer',
      original_name: 'Snowpiercer',
      overview:
        'More than seven years after the world has become a frozen wasteland, the remnants of humanity inhabit a gigantic, perpetually-moving train that circles the globe as class warfare, social injustice and the politics of survival play out.',
      poster_path: '/exKzfiKzMdQBHrdd7zNmKauJkbg.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [10765],
      popularity: 337.419,
      first_air_date: '2020-05-17',
      vote_average: 7.4,
      vote_count: 1169,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/2WBO3C7CjsOTT5wgi9Inn5iQhVv.jpg',
      id: 46195,
      name: 'Monogatari',
      original_name: '化物語',
      overview:
        'Although there are still traces of the brief period he became a vampire, third-year high school student Koyomi Araragi is human again. He happens upon others with their own supernatural problems and finds that he can empathize. Koyomi becomes involved in their lives, seeking to help them and occasionally asking for advice from Meme Oshino, the homeless man who helped him become human again.',
      poster_path: '/zCEjjb1NH3LLsWeZx47wOeqkezf.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'ja',
      genre_ids: [16, 35, 18, 9648],
      popularity: 724.616,
      first_air_date: '2009-07-03',
      vote_average: 8.133,
      vote_count: 446,
      origin_country: ['JP'],
    },
    {
      backdrop_path: '/4lIC1dtzEEBc1oeSK5gy2qBqASR.jpg',
      id: 258280,
      name: 'Dashing Youth',
      original_name: '少年白马醉春风',
      overview: '',
      poster_path: '/dDceSh1sd6b9Tkd3wnZtIZmsJOv.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'zh',
      genre_ids: [18],
      popularity: 23.941,
      first_air_date: '2024-07-19',
      vote_average: 0,
      vote_count: 0,
      origin_country: ['CN'],
    },
    {
      backdrop_path: '/qzi8rTS2KpkrYNWxC1tt7xkRlTY.jpg',
      id: 156933,
      name: 'Presumed Innocent',
      original_name: 'Presumed Innocent',
      overview:
        "A horrific murder upends the Chicago Prosecuting Attorney's Office when one of its own is suspected of the crime—leaving the accused fighting to keep his family together.",
      poster_path: '/7MXg0BxuSRWz2yKc03M40du2mrc.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [18, 9648],
      popularity: 648.082,
      first_air_date: '2024-06-11',
      vote_average: 8.1,
      vote_count: 109,
      origin_country: ['US'],
    },
    {
      backdrop_path: '/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg',
      id: 1399,
      name: 'Game of Thrones',
      original_name: 'Game of Thrones',
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
      media_type: 'tv',
      adult: false,
      original_language: 'en',
      genre_ids: [10765, 18, 10759],
      popularity: 1657.301,
      first_air_date: '2011-04-17',
      vote_average: 8.453,
      vote_count: 23462,
      origin_country: ['US'],
    },
  ];

  constructor() {}

  @ViewChild(HeroCardsComponent) heroCards!: HeroCardsComponent;

  ngAfterViewInit(): void {
    this.heroCards.startCardsScrollBasedAnimation();
  }
  ngOnDestroy(): void {
    this.heroCards.stopCardsScrollBasedAnimation();
  }
}

export interface Movie {
  backdrop_path: string;
  id: number;
  title: string;
  original_title: string;
  overview: string;
  poster_path: string;
  media_type: 'movie';
  adult: boolean;
  original_language: string;
  genre_ids: number[];
  popularity: number;
  release_date: string;
  video: boolean;
  vote_average: number;
  vote_count: number;
}

export interface Series {
  backdrop_path: string;
  id: number;
  name: string;
  original_name: string;
  overview: string;
  poster_path: string;
  media_type: string;
  adult: boolean;
  original_language: string;
  genre_ids: number[];
  popularity: number;
  first_air_date: string;
  vote_average: number;
  vote_count: number;
  origin_country: string[];
}
