import { AfterViewInit, Component, OnDestroy, ViewChild } from '@angular/core';
import { HeroCardsComponent } from './hero-cards/hero-cards.component';
import { ButtonsHeaderComponent } from '../shared/components/buttons-header/buttons-header.component';
import { CardsSectionComponent } from '../shared/components/cards-section/cards-section.component';
import { HeaderButton } from '../shared/components/buttons-header/buttons-header.component';

@Component({
  selector: 'app-home',
  standalone: true,
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
  imports: [ButtonsHeaderComponent, HeroCardsComponent, CardsSectionComponent],
})
export class HomeComponent implements AfterViewInit, OnDestroy {
  protected userPhoto: string = '';

  private tmdbEntities = {
    persons: [
      {
        id: 1905,
        name: 'Vincent Price',
        original_name: 'Vincent Price',
        media_type: 'person',
        adult: false,
        popularity: 21.091,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/mgKrmTGuKcWH7BalBQ78kyd3dot.jpg',
        known_for: [
          {
            backdrop_path: '/3Nn5BOM1EVw1IYrv6MsbOS6N1Ol.jpg',
            id: 162,
            title: 'Edward Scissorhands',
            original_title: 'Edward Scissorhands',
            overview:
              'A small suburban town receives a visit from a castaway unfinished science experiment named Edward.',
            poster_path: '/e0FqKFvGPdQNWG8tF9cZBtev9Em.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [14, 18, 10749],
            popularity: 55.806,
            release_date: '1990-12-07',
            video: false,
            vote_average: 7.717,
            vote_count: 12620,
          },
          {
            backdrop_path: '/7OY9BSM5CYQiHvonQhlQiJGaEnL.jpg',
            id: 32085,
            title: 'Vincent',
            original_title: 'Vincent',
            overview:
              'Young Vincent Malloy dreams of being just like Vincent Price and loses himself in macabre daydreams that annoy his mother.',
            poster_path: '/jRIFN6WJOeJUInJlzRUEb6E1vkB.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [16, 14],
            popularity: 9.9,
            release_date: '1982-10-01',
            video: false,
            vote_average: 7.887,
            vote_count: 833,
          },
          {
            backdrop_path: '/ijCfzdRLhrdu9OUIaPsVt08ogT5.jpg',
            id: 9994,
            title: 'The Great Mouse Detective',
            original_title: 'The Great Mouse Detective',
            overview:
              "When the diabolical Professor Ratigan kidnaps London's master toymaker, the brilliant master of disguise Basil of Baker Street and his trusted sidekick Dawson try to elude the ultimate trap and foil the perfect crime.",
            poster_path: '/9uDr7vfjCFr39KGCcqrk44Cg7fQ.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [16, 10751, 12, 9648],
            popularity: 20.109,
            release_date: '1986-07-02',
            video: false,
            vote_average: 7.056,
            vote_count: 1591,
          },
        ],
      },
      {
        id: 5788,
        name: 'James Cagney',
        original_name: 'James Cagney',
        media_type: 'person',
        adult: false,
        popularity: 8.339,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/haDKecHGGb1qh8gAoR3ExiJlujn.jpg',
        known_for: [
          {
            backdrop_path: '/cap8458wFeRCJSKxL758dI82TRK.jpg',
            id: 15794,
            title: 'White Heat',
            original_title: 'White Heat',
            overview:
              'A psychopathic criminal with a mother complex makes a daring break from prison and then leads his old gang in a chemical plant payroll heist. After the heist, events take a crazy turn.',
            poster_path: '/4ekAK25fz1FDzRUHuJs171uiVaI.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [80, 18, 53],
            popularity: 14.707,
            release_date: '1949-09-02',
            video: false,
            vote_average: 7.662,
            vote_count: 454,
          },
          {
            backdrop_path: '/vo3cB6xkMswMz9gB2X517TmxmI2.jpg',
            id: 430,
            title: 'One, Two, Three',
            original_title: 'One, Two, Three',
            overview:
              'C.R. MacNamara is a managing director for Coca Cola in West Berlin during the Cold War, just before the Wall is put up. When Scarlett, the rebellious daughter of his boss, comes to West Berlin, MacNamara has to look after her, but this turns out to be a difficult task when she reveals to be married to a communist.',
            poster_path: '/yWQE227ub1frfnjP5HZy0wLF0wu.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [35],
            popularity: 14.14,
            release_date: '1961-12-15',
            video: false,
            vote_average: 7.524,
            vote_count: 357,
          },
          {
            backdrop_path: '/oXLaGV0VOqQhXdUmQpm6KGsSpu1.jpg',
            id: 17687,
            title: 'The Public Enemy',
            original_title: 'The Public Enemy',
            overview:
              'Two young Chicago hoodlums, Tom Powers and Matt Doyle, rise up from their poverty-stricken slum life to become petty thieves, bootleggers and cold-blooded killers. But with street notoriety and newfound wealth, the duo feels the heat from the cops and rival gangsters both. Despite his ruthless criminal reputation, Tom tries to remain connected to his family, however, gang warfare and the need for revenge eventually pull him away.',
            poster_path: '/vVxdaRMprQO2DM4AFyJ6C4qZSFO.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [80, 18],
            popularity: 12.349,
            release_date: '1931-04-23',
            video: false,
            vote_average: 7.236,
            vote_count: 328,
          },
        ],
      },
      {
        id: 1547,
        name: 'Bela Lugosi',
        original_name: 'Bela Lugosi',
        media_type: 'person',
        adult: false,
        popularity: 11.697,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/fwimu7WKcaJXIjaDwYQg42GxUxa.jpg',
        known_for: [
          {
            backdrop_path: '/cemjdP7HrUyJAry85vRT19Hidbi.jpg',
            id: 138,
            title: 'Dracula',
            original_title: 'Dracula',
            overview:
              'British estate agent Renfield travels to Transylvania to meet with the mysterious Count Dracula, who is interested in leasing a castle in London and is, unbeknownst to Renfield, a vampire. After Dracula enslaves Renfield and drives him to insanity, the pair sail to London together, and as Dracula begins preying on London socialites, the two become the subject of study for a supernaturalist professor, Abraham Van Helsing.',
            poster_path: '/ueVSPt7vAba0XScHWTDWS5tNxYX.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [27],
            popularity: 28.578,
            release_date: '1931-02-12',
            video: false,
            vote_average: 7.2,
            vote_count: 1145,
          },
          {
            backdrop_path: '/9tcIzvTfIYkoxjLiTcaXdMwfzT6.jpg',
            id: 26860,
            title: 'White Zombie',
            original_title: 'White Zombie',
            overview:
              'In Haiti, a wealthy landowner convinces a sorcerer to lure the American woman he has fallen for away from her fiance, only to have the madman decide to keep the woman for himself, as a zombie.',
            poster_path: '/s5DnfWHGeCExlweIFF4JOHKyx3H.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [27],
            popularity: 8.756,
            release_date: '1932-07-28',
            video: false,
            vote_average: 5.884,
            vote_count: 245,
          },
          {
            backdrop_path: '/mixXbH4zDo2cGx5WZGwV5mxkDA0.jpg',
            id: 24106,
            title: 'The Black Cat',
            original_title: 'The Black Cat',
            overview:
              'After a road accident in Hungary, the American honeymooners Joan and Peter and the enigmatic Dr. Werdegast find refuge in the house of the famed architect Hjalmar Poelzig, who shares a dark past with the doctor.',
            poster_path: '/QTH3dkeDGTBRBmsY0A7STpsNN4.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [27],
            popularity: 9.954,
            release_date: '1934-05-07',
            video: false,
            vote_average: 6.668,
            vote_count: 259,
          },
        ],
      },
      {
        id: 1269,
        name: 'Kevin Costner',
        original_name: 'Kevin Costner',
        media_type: 'person',
        adult: false,
        popularity: 76.762,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/bykmxJHLfbFM3NT05RZXhx8YTzF.jpg',
        known_for: [
          {
            backdrop_path: '/i1oWUGVDNBhGBykcCRBlX326udb.jpg',
            id: 117,
            title: 'The Untouchables',
            original_title: 'The Untouchables',
            overview:
              'Elliot Ness, an ambitious prohibition agent, is determined to take down Al Capone. In order to achieve this goal, he forms a group given the nickname “The Untouchables”.',
            poster_path: '/jB8ROzQOr3p4ygSzyPjLhUqCOFu.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [80, 36, 53],
            popularity: 36.086,
            release_date: '1987-06-03',
            video: false,
            vote_average: 7.772,
            vote_count: 5462,
          },
          {
            backdrop_path: '/44Ntdh1CuV83bkBRq8zOUeS3O0P.jpg',
            id: 581,
            title: 'Dances with Wolves',
            original_title: 'Dances with Wolves',
            overview:
              "Wounded Civil War soldier John Dunbar tries to commit suicide—and becomes a hero instead. As a reward, he's assigned to his dream post, a remote junction on the Western frontier, and soon makes unlikely friends with the local Sioux tribe.",
            poster_path: '/cvaBVpS0GzKqBd63pFT8f1E8OKv.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [12, 18, 37],
            popularity: 54.368,
            release_date: '1990-03-30',
            video: false,
            vote_average: 7.851,
            vote_count: 4101,
          },
          {
            backdrop_path: '/vHLyDk0uRb72xFeQjU1KJZ3g7hQ.jpg',
            id: 9804,
            title: 'Waterworld',
            original_title: 'Waterworld',
            overview:
              "In a futuristic world where the polar ice caps have melted and made Earth a liquid planet, a beautiful barmaid rescues a mutant seafarer from a floating island prison. They escape, along with her young charge, Enola, and sail off aboard his ship. But the trio soon becomes the target of a menacing pirate who covets the map to 'Dryland'—which is tattooed on Enola's back.",
            poster_path: '/f4Q6BKm1lv9u5xoffbIIwrOYf6z.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [12, 28, 878],
            popularity: 42.459,
            release_date: '1995-07-28',
            video: false,
            vote_average: 6.2,
            vote_count: 3577,
          },
        ],
      },
      {
        id: 3732609,
        name: 'Joel Haver',
        original_name: 'Joel Haver',
        media_type: 'person',
        adult: false,
        popularity: 5.104,
        gender: 2,
        known_for_department: 'Directing',
        profile_path: '/j3S8SPHjKeSY0QMzg9SAxURY2HU.jpg',
        known_for: [
          {
            backdrop_path: '/nlB8sZg5eqwn0K3pk3h5CxLLkB5.jpg',
            id: 1019105,
            title: 'The Paloni Show! Halloween Special!',
            original_title: 'The Paloni Show! Halloween Special!',
            overview:
              'Leroy, Reggie and Cheruce Paloni host a Halloween special full of spooky shorts from a group of up-and-coming animators.',
            poster_path: '/y9LjwvEZDFWojjyKXdHb20A6526.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [16, 35, 27],
            popularity: 22.158,
            release_date: '2022-10-17',
            video: false,
            vote_average: 6.1,
            vote_count: 29,
          },
        ],
      },
      {
        id: 2963,
        name: 'Nicolas Cage',
        original_name: 'Nicolas Cage',
        media_type: 'person',
        adult: false,
        popularity: 87.636,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/ar33qcWbEgREn07ZpXv5Pbj8hbM.jpg',
        known_for: [
          {
            backdrop_path: '/rmDKJu0IEETUm3tyRwCQTk48MvE.jpg',
            id: 49519,
            title: 'The Croods',
            original_title: 'The Croods',
            overview:
              'The prehistoric Croods family live in a particularly dangerous moment in time. Patriarch Grug, his mate Ugga, teenage daughter Eep, son Thunk, and feisty Gran gather food by day and huddle together in a cave at night. When a more evolved caveman named Guy arrives on the scene, Grug is distrustful, but it soon becomes apparent that Guy is correct about the impending destruction of their world.',
            poster_path: '/hkjPDCe6qmPcrkinqTgv0ygcrHg.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [16, 12, 10751, 14, 35, 28],
            popularity: 66.187,
            release_date: '2013-03-15',
            video: false,
            vote_average: 6.916,
            vote_count: 6924,
          },
          {
            backdrop_path: '/xXWT0je8dTFFNBq6P2CeTZkPUu2.jpg',
            id: 2059,
            title: 'National Treasure',
            original_title: 'National Treasure',
            overview:
              "Modern treasure hunters, led by archaeologist Ben Gates, search for a chest of riches rumored to have been stashed away by George Washington, Thomas Jefferson and Benjamin Franklin during the Revolutionary War. The chest's whereabouts may lie in secret clues embedded in the Constitution and the Declaration of Independence, and Gates is in a race to find the gold before his enemies do.",
            poster_path: '/pxL6E4GBOPUG6CdkO9cUQN5VMwI.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [12, 28, 53, 9648],
            popularity: 38.4,
            release_date: '2004-11-19',
            video: false,
            vote_average: 6.634,
            vote_count: 6173,
          },
          {
            backdrop_path: '/7zS58YPAw002RNejOF1vNB3XHbW.jpg',
            id: 1250,
            title: 'Ghost Rider',
            original_title: 'Ghost Rider',
            overview:
              "In order to save his dying father, young stunt cyclist Johnny Blaze sells his soul to Mephistopheles and sadly parts from the pure-hearted Roxanne Simpson, the love of his life. Years later, Johnny's path crosses again with Roxanne, now a go-getting reporter, and also with Mephistopheles, who offers to release Johnny's soul if Johnny becomes the fabled, fiery 'Ghost Rider'.",
            poster_path: '/8LaVQiXBsnlo7MXCPK1nXTVARUZ.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [53, 28, 14],
            popularity: 59.886,
            release_date: '2007-01-15',
            video: false,
            vote_average: 5.568,
            vote_count: 5762,
          },
        ],
      },
      {
        id: 12799,
        name: 'Jeremy Piven',
        original_name: 'Jeremy Piven',
        media_type: 'person',
        adult: false,
        popularity: 36.918,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/pqdR8zqAWF87chGYlbdYr0YfC7g.jpg',
        known_for: [
          {
            backdrop_path: '/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg',
            id: 920,
            title: 'Cars',
            original_title: 'Cars',
            overview:
              "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
            poster_path: '/abW5AzHDaIK1n9C36VdAeOwORRA.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [16, 12, 35, 10751],
            popularity: 87.131,
            release_date: '2006-06-08',
            video: false,
            vote_average: 6.973,
            vote_count: 13635,
          },
          {
            backdrop_path: '/rqpPH5At8AzYUYR2GneC0x65GeK.jpg',
            id: 9778,
            title: 'Serendipity',
            original_title: 'Serendipity',
            overview:
              'Although strangers Sara and Jonathan are both already in relationships, they realize they have genuine chemistry after a chance encounter – but part company soon after. Years later, they each yearn to reunite, despite being destined for the altar. But to give true love a chance, they have to find one another again.',
            poster_path: '/srCE5lEIjVEG5eqWg9JcjZCK1aQ.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [35, 10749, 18],
            popularity: 16.342,
            release_date: '2001-10-05',
            video: false,
            vote_average: 6.939,
            vote_count: 1857,
          },
          {
            backdrop_path: '/6bNQuKFJIamipvYclG4MEbDSLM5.jpg',
            id: 93837,
            title: 'So Undercover',
            original_title: 'So Undercover',
            overview:
              'When the FBI hires her to go undercover at a college sorority, Molly Morris (Miley Cyrus) must transform herself from a tough, streetwise private investigator to a refined, sophisticated university girl to help protect the daughter of a one-time Mobster. With several suspects on her list, Molly unexpectedly discovers that not everyone is who they appear to be, including herself.',
            poster_path: '/abR6e0FaWwwcEJEM4PY5VvjwBr1.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 35],
            popularity: 16.919,
            release_date: '2012-12-06',
            video: false,
            vote_average: 6.2,
            vote_count: 1095,
          },
        ],
      },
      {
        id: 550843,
        name: 'Elizabeth Olsen',
        original_name: 'Elizabeth Olsen',
        media_type: 'person',
        adult: false,
        popularity: 32.291,
        gender: 1,
        known_for_department: 'Acting',
        profile_path: '/wIU675y4dofIDVuhaNWPizJNtep.jpg',
        known_for: [
          {
            backdrop_path: '/lOr9NKxh4vMweufMOUDJjJhCRHW.jpg',
            id: 85271,
            name: 'WandaVision',
            original_name: 'WandaVision',
            overview:
              'Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.',
            poster_path: '/glKDfE6btIRcVB5zrjspRIs4r52.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'en',
            genre_ids: [10765, 9648, 18],
            popularity: 167.824,
            first_air_date: '2021-01-15',
            vote_average: 8.234,
            vote_count: 11797,
            origin_country: ['US'],
          },
          {
            backdrop_path: '/zCjZfevPFBbOh2SAx2syIBHSqEI.jpg',
            id: 124905,
            title: 'Godzilla',
            original_title: 'Godzilla',
            overview:
              'Ford Brody, a Navy bomb expert, has just reunited with his family in San Francisco when he is forced to go to Japan to help his estranged father, Joe. Soon, both men are swept up in an escalating crisis when an ancient alpha predator arises from the sea to combat malevolent adversaries that threaten the survival of humanity. The creatures leave colossal destruction in their wake, as they make their way toward their final battleground: San Francisco.',
            poster_path: '/zokD6uxR2iWfYM3Y84yGJvnNTK7.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 18, 878],
            popularity: 140.896,
            release_date: '2014-05-14',
            video: false,
            vote_average: 6.339,
            vote_count: 8941,
          },
          {
            backdrop_path: '/gUNRlH66yNDH3NQblYMIwgZXJ2u.jpg',
            id: 453395,
            title: 'Doctor Strange in the Multiverse of Madness',
            original_title: 'Doctor Strange in the Multiverse of Madness',
            overview:
              'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
            poster_path: '/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [14, 28, 12],
            popularity: 105.603,
            release_date: '2022-05-04',
            video: false,
            vote_average: 7.298,
            vote_count: 8790,
          },
        ],
      },
      {
        id: 992366,
        name: 'Maia Mitchell',
        original_name: 'Maia Mitchell',
        media_type: 'person',
        adult: false,
        popularity: 16.14,
        gender: 1,
        known_for_department: 'Acting',
        profile_path: '/xGYAwTUFVpEvIyagMaeh9pBVVj0.jpg',
        known_for: [
          {
            backdrop_path: '/aWas3hZ8DKvfKxLe3dQVpB758eA.jpg',
            id: 502292,
            title: 'The Last Summer',
            original_title: 'The Last Summer',
            overview:
              'Standing on the precipice of adulthood, a group of friends navigate new relationships, while reexamining others, during their final summer before college.',
            poster_path: '/nAn3MRAUwbjVApN3qYkvsTEOAvx.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [10749, 35],
            popularity: 23.136,
            release_date: '2019-05-03',
            video: false,
            vote_average: 6.003,
            vote_count: 1355,
          },
          {
            backdrop_path: '/znjVe07uk6VLIMK9Lsd2kGsq97B.jpg',
            id: 177888,
            title: 'Teen Beach Movie',
            original_title: 'Teen Beach Movie',
            overview:
              'Life\'s a beach for surfers Brady and McKenzie – until a rogue wave magically transports them inside the classic \'60s beach party flick, "Wet Side Story," where a full-blown rivalry between bikers and surfers threatens to erupt. There, amidst a sea of surfing, singing and dancing, Brady and Mack accidentally change the storyline, and the film’s dreamy hero and heroine fall for them instead of for each other!',
            poster_path: '/ywX8INXLshhf94pyxc8wE2MO4aT.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [10751, 10402, 10770, 35],
            popularity: 20.698,
            release_date: '2013-08-07',
            video: false,
            vote_average: 6.875,
            vote_count: 905,
          },
          {
            backdrop_path: '/vBBI4eAc9Hs344kko5eqPZTajLl.jpg',
            id: 325189,
            title: 'Teen Beach 2',
            original_title: 'Teen Beach 2',
            overview:
              'When characters from the movie musical “Wet Side Story” get stuck in the real world, teens Brady and Mack must find a way to return them home.',
            poster_path: '/3h1QyNjuuD6fwuMoFR8IG206Dan.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [10770, 10751, 35, 14],
            popularity: 21.962,
            release_date: '2015-06-26',
            video: false,
            vote_average: 6.75,
            vote_count: 577,
          },
        ],
      },
      {
        id: 64930,
        name: 'Bob Newhart',
        original_name: 'Bob Newhart',
        media_type: 'person',
        adult: false,
        popularity: 39.79,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/kj9lWESb2cC3beTypLKTCH0HipH.jpg',
        known_for: [
          {
            backdrop_path: '/dSlofjxxcTSLmnH6602WsSSELU5.jpg',
            id: 11319,
            title: 'The Rescuers',
            original_title: 'The Rescuers',
            overview:
              "What can two little mice possibly do to save an orphan girl who's fallen into evil hands? With a little cooperation and faith in oneself, anything is possible! As members of the mouse-run International Rescue Aid Society, Bernard and Miss Bianca respond to orphan Penny's call for help. The two mice search for clues with the help of an old cat named Rufus.",
            poster_path: '/49rGpB2x6AFB83SC4IBl9foRIGp.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [14, 10751, 16, 12],
            popularity: 30.69,
            release_date: '1977-06-22',
            video: false,
            vote_average: 6.774,
            vote_count: 2416,
          },
          {
            backdrop_path: '/5nhp41gx49vXjwXuDXJwQrRFsng.jpg',
            id: 10719,
            title: 'Elf',
            original_title: 'Elf',
            overview:
              "When young Buddy falls into Santa's gift sack on Christmas Eve, he's transported back to the North Pole and raised as a toy-making elf by Santa's helpers. But as he grows into adulthood, he can't shake the nagging feeling that he doesn't belong. Buddy vows to visit Manhattan and find his real dad, a workaholic.",
            poster_path: '/oOleziEempUPu96jkGs0Pj6tKxj.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [35, 10751, 14],
            popularity: 56.488,
            release_date: '2003-10-09',
            video: false,
            vote_average: 6.7,
            vote_count: 3911,
          },
          {
            backdrop_path: '/hYXC1auWlCqTzY0KHt5a29sw8pJ.jpg',
            id: 11135,
            title: 'The Rescuers Down Under',
            original_title: 'The Rescuers Down Under',
            overview:
              "A lawless poacher wants to capture a majestic and rare golden eagle, so he kidnaps the boy who knows where to find the bird. Not to worry -- the Rescue Aid Society's top agents, heroic mice Miss Bianca and Bernard, fly to Australia to save the day. Accompanying the fearless duo are bumbling albatross Wilbur and local field operative Jake the Kangaroo Rat.",
            poster_path: '/n3pkIU9E6MOmr7bqrEq3GG1Be7P.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [16, 12, 10751, 14],
            popularity: 8.871,
            release_date: '1990-11-16',
            video: false,
            vote_average: 6.623,
            vote_count: 1237,
          },
        ],
      },
      {
        id: 184924,
        name: 'Frances Tomelty',
        original_name: 'Frances Tomelty',
        media_type: 'person',
        adult: false,
        popularity: 16.823,
        gender: 1,
        known_for_department: 'Acting',
        profile_path: '/nZPZijCmdr5HvpiprTDAEbpwtlU.jpg',
        known_for: [
          {
            backdrop_path: '/xaHEopBVf5BZCrHiSdzvYgA3vdj.jpg',
            id: 22215,
            title: 'Chéri',
            original_title: 'Chéri',
            overview:
              'The son of a courtesan retreats into a fantasy world after being forced to end his relationship with the older woman who educated him in the ways of love.',
            poster_path: '/b35rv11ebJdqCe5chVmSUZ0RIlX.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [18, 35, 10749],
            popularity: 11.621,
            release_date: '2009-04-08',
            video: false,
            vote_average: 6.088,
            vote_count: 199,
          },
          {
            backdrop_path: '/j8ajhpIpX2mR3SEfc6kSsdZefGR.jpg',
            id: 31651,
            title: 'The Field',
            original_title: 'The Field',
            overview:
              '"Bull" McCabe\'s family has farmed a field for generations, sacrificing much in the name of the land. When the widow who owns the field decides to sell it in a public auction, McCabe knows that he must own it. While no local dare bid against him, a wealthy American decides he requires the field to build a highway. "Bull" and his son decide they must try to convince the American to let go of his ambition and return home, but the consequences of their plot prove sinister.',
            poster_path: '/ppF5pUheNoL0EPuGRIEnHz1ewp7.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [18],
            popularity: 7.56,
            release_date: '1990-09-21',
            video: false,
            vote_average: 7.023,
            vote_count: 86,
          },
          {
            backdrop_path: '/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg',
            id: 60574,
            name: 'Peaky Blinders',
            original_name: 'Peaky Blinders',
            overview:
              'A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby, who means to move up in the world.',
            poster_path: '/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg',
            media_type: 'tv',
            adult: false,
            original_language: 'en',
            genre_ids: [18, 80],
            popularity: 1722.217,
            first_air_date: '2013-09-12',
            vote_average: 8.538,
            vote_count: 9671,
            origin_country: ['GB'],
          },
        ],
      },
      {
        id: 2710789,
        name: 'Seung Ha',
        original_name: 'Seung Ha',
        media_type: 'person',
        adult: false,
        popularity: 56.51,
        gender: 1,
        known_for_department: 'Acting',
        profile_path: '/nvSJiHakYrDa3CedKSVOEsbLLX8.jpg',
        known_for: [
          {
            backdrop_path: '/rnWEut44AFaC4G7H3nSwzKVIyV8.jpg',
            id: 724106,
            title: "R-Rated Idol Seung-ha's Sex Scandal",
            original_title: '18금 아이돌 승하의 섹스 스캔들',
            overview:
              "When they were young, Min-joo and Seo-yeon cared for each other and were closer than brothers and sisters. However, she accidentally learns about Seo-yeon's tutor, Woo-hyeon, and because of this man, their 10-year friendship starts to become shaky. Meanwhile, Jeong-soo is hurt in seeing Min-joo like that, and so he distanced himself from Min-joo. Because of Min-joo and Seo-yeon's misunderstanding, Jeong-soo who couldn't care much might just leave so Min-joo tries to break up with the help of Seo-yeon. While in the process of breaking up, Min-joo and Seo-yeon went back to their close relationship.  The love of women who have been separated because of man, and the two men's friendship is comically drawn.",
            poster_path: '/btpk0Y0m9MjvMCfgrW0i0d7fpd1.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'ko',
            genre_ids: [18, 10749],
            popularity: 19.506,
            release_date: '2020-07-17',
            video: false,
            vote_average: 6.826,
            vote_count: 46,
          },
          {
            backdrop_path: '/lQYIamZ7SZR4Ufq7mKUwPZtBYWL.jpg',
            id: 852370,
            title: "Idol Seungha's R-Rated Film Shooting",
            original_title: '아이돌 승하의 19금 AV를 찍자',
            overview:
              "Film producer Na-eun and director Yeong-tae are on the verge of shelving out cash for an adult film production. They're too busy blaming each other for the messed-up filming. Before another filming begins, Na-eun suggests Yeong-tae to become an actor himself and practice filming. Na-eun leads the shy Yeong-tae very skillfully. How far will the practice go...?",
            poster_path: '/4CVYNzGwTMgOKxycg2LQO9slwfH.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'ko',
            genre_ids: [18],
            popularity: 36.268,
            release_date: '2021-06-24',
            video: false,
            vote_average: 6.603,
            vote_count: 34,
          },
          {
            backdrop_path: '/xZ02qIyNEPXSDJn89LFeQS3FuvX.jpg',
            id: 724108,
            title: "R-Rated Idol Seung-ha's Fancy Walk",
            original_title: '18금 아이돌 승하의 화려한 외출',
            overview:
              "Seo-yeon is being tutored by Woo-hyeon who is younger than her. She grew interested in her tutor, Woo-hyun, the first time she met him, and he is also fond of Seo-yeon. Seo-yeon succeeded in seducing Woo-hyeon with the help of her friend Min-joo. Even if Min-joo is aware of what Seo-yeon feels, she approaches Woo-hyeon. Seo-yeon gets mad at her best friend when she met Woo-hyeon. Min-joo, aware of the fact that it's her faultis also angered by Seo-yeon's appearance and tells her to meet Jeong-soo, her friend. Seo-yeon is also angry and tells Min-joo that she have to meet Jeong-soo as well. A bittersweet story about a man who is a very close friend is just about to start.",
            poster_path: '/l0jd4v2490rC9oqwnEOVJ6KNK3x.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'ko',
            genre_ids: [18, 10749],
            popularity: 17.336,
            release_date: '2020-07-01',
            video: false,
            vote_average: 7.667,
            vote_count: 15,
          },
        ],
      },
      {
        id: 1336,
        name: 'Jet Li',
        original_name: 'Jet Li',
        media_type: 'person',
        adult: false,
        popularity: 45.036,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/c4s8INzU0ZAujCQ1YmphCmcsNzl.jpg',
        known_for: [
          {
            backdrop_path: '/eRvo5lY5SRsm163Csqtd7lRxaAE.jpg',
            id: 27578,
            title: 'The Expendables',
            original_title: 'The Expendables',
            overview:
              'Barney Ross leads a band of highly skilled mercenaries including knife enthusiast Lee Christmas, a martial arts expert Yin Yang, heavy weapons specialist Hale Caesar, demolitionist Toll Road, and a loose-cannon sniper Gunner Jensen. When the group is commissioned by the mysterious Mr. Church to assassinate the dictator of a small South American island, Barney and Lee visit the remote locale to scout out their opposition and discover the true nature of the conflict engulfing the city.',
            poster_path: '/j09ZkH6R4JWVylBcDai1laCmGw7.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [53, 12, 28],
            popularity: 63.428,
            release_date: '2010-08-03',
            video: false,
            vote_average: 6.243,
            vote_count: 7574,
          },
          {
            backdrop_path: '/41QdmNKbwmVD7R6A7hMqMe9FYMy.jpg',
            id: 76163,
            title: 'The Expendables 2',
            original_title: 'The Expendables 2',
            overview:
              'Mr. Church reunites the Expendables for what should be an easy paycheck, but when one of their men is murdered on the job, their quest for revenge puts them deep in enemy territory and up against an unexpected threat.',
            poster_path: '/4EBO8aIeP2bF1jGpwbuRS4CFMca.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 12, 53],
            popularity: 51.381,
            release_date: '2012-08-08',
            video: false,
            vote_average: 6.344,
            vote_count: 6580,
          },
          {
            backdrop_path: '/p31yIpOO7VLP9lJa3YH0sLX9q3H.jpg',
            id: 79,
            title: 'Hero',
            original_title: '英雄',
            overview:
              "During China's Warring States period, a district prefect arrives at the palace of Qin Shi Huang, claiming to have killed the three assassins who had made an attempt on the king's life three years ago.",
            poster_path: '/1NBtOH3KPU9UUp1vzVHJ8qzdW88.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'zh',
            genre_ids: [18, 12, 28, 36],
            popularity: 22.14,
            release_date: '2002-07-22',
            video: false,
            vote_average: 7.5,
            vote_count: 2183,
          },
        ],
      },
      {
        id: 25246,
        name: 'Andy Lau',
        original_name: 'Andy Lau',
        media_type: 'person',
        adult: false,
        popularity: 35.582,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/3bs0J3KwnAIocT1RxlT9akltcEt.jpg',
        known_for: [
          {
            backdrop_path: '/iiDGA97Kqt2dVU1deXQF06USBRu.jpg',
            id: 10775,
            title: 'Infernal Affairs',
            original_title: '無間道',
            overview:
              'Chan Wing Yan, a young police officer, has been sent undercover as a mole in the local mafia. Lau Kin Ming, a young mafia member, infiltrates the police force. Years later, their older counterparts, Chen Wing Yan and Inspector Lau Kin Ming, respectively, race against time to expose the mole within their midst.',
            poster_path: '/gix9thDBXfjJ8M7rYbihqbQGBcP.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'cn',
            genre_ids: [18, 28, 53, 80, 9648],
            popularity: 34.255,
            release_date: '2002-12-12',
            video: false,
            vote_average: 7.82,
            vote_count: 1585,
          },
          {
            backdrop_path: '/jmg9qYhzPZdYuNaOZr5xrQPK6cQ.jpg',
            id: 311324,
            title: 'The Great Wall',
            original_title: 'The Great Wall',
            overview:
              'European mercenaries searching for black powder become embroiled in the defense of the Great Wall of China against a horde of monstrous creatures.',
            poster_path: '/p70dq1YxabemdZDm5K6Q8G10wSn.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 12, 14],
            popularity: 100.279,
            release_date: '2016-12-16',
            video: false,
            vote_average: 6.024,
            vote_count: 5009,
          },
          {
            backdrop_path: '/jea4adbYk407PhYK9uhWjihPYAv.jpg',
            id: 9550,
            title: 'House of Flying Daggers',
            original_title: '十面埋伏',
            overview:
              'In 9th century China, a corrupt government wages war against a rebel army called the Flying Daggers. A romantic warrior breaks a beautiful rebel out of prison to help her rejoin her fellows, but things are not what they seem.',
            poster_path: '/93feGsGiCtG5ymrRcErUgBsdo6v.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'zh',
            genre_ids: [12, 18, 28],
            popularity: 21.849,
            release_date: '2004-05-19',
            video: false,
            vote_average: 7.282,
            vote_count: 1571,
          },
        ],
      },
      {
        id: 3165040,
        name: 'Rika',
        original_name: 'Rika',
        media_type: 'person',
        adult: false,
        popularity: 59.251,
        gender: 1,
        known_for_department: 'Acting',
        profile_path: '/vwYqrhcSRVrnra4S0NopnywN8rK.jpg',
        known_for: [
          {
            backdrop_path: '/oubeM1HVaEpS1fk0L2qf12xWFR6.jpg',
            id: 784941,
            title: 'Taming The Younger Sister-in-Law',
            original_title: '처제 길들이기',
            overview:
              "One day, Min-sang who is not that handsome becomes a huge success because of a webtoon. Then he gets a sexy wife, Yu-ra, for himself. Min-sang is having a dream-like marriage with Yura. It has been a perfect day except for his sister-in-law Yu-mi, who hates her ugly self. Accidentally, he learned of his wife's dark past through his sister-in-law's diary, and this leads to a reversal of the relationship with her sister-in-law. Min-sang began to demand excessive demands from his sister-in-law, and Yu-mi began to accept them. Where will the end of the relationship between Min-sang, Yu-ra, and Yu-mi lead?",
            poster_path: '/dF5SiTe94NkkGJNinB6Mz2izKy0.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'ko',
            genre_ids: [18, 10749],
            popularity: 38.125,
            release_date: '2020-12-11',
            video: false,
            vote_average: 6.143,
            vote_count: 7,
          },
          {
            backdrop_path: '/yocikArliqCHUEW4dL9XTD26fKJ.jpg',
            id: 852363,
            title: "18 Year Old Model Rika's Fancy Walk",
            original_title: '18 모델 리카의 화려한 외출',
            overview:
              "At first, Yoo-jeong and Min-soo really loved each other. However, in a few months, there is a period of boredom between the two. Two people face each other and don't eat. Yoo-jeong confides her worries to her friend So-hyeon. But So-hyeon never misses the chance and confesses her feelings to Min-soo. Min-soo’s heart is shaken by So-hyeon. I'm meeting So-hyeon secretly. After a secret meeting with So-hyeon, he finds some time to relax.",
            poster_path: '/neTFIO3YIDcH6p8e8a0ka0V21fO.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'ko',
            genre_ids: [18, 10749],
            popularity: 12.913,
            release_date: '2020-09-28',
            video: false,
            vote_average: 5,
            vote_count: 4,
          },
          {
            backdrop_path: null,
            id: 773804,
            title: 'Female Urologists 3',
            original_title: '비뇨기과 여의사들3',
            overview:
              "Haeil, wounded by his wife's words of 'premature ejaculation', goes to a urology department. But because the doctor is a woman, she is so surprised and embarrassed that she tries to go out. Then, a word from a woman doctor catches him. \"How long will you live with premature ejaculation?\". After that, after receiving special treatment, the beautiful female doctor Jeongyeon and glamor nurse Mijoo, Haeil gradually became a man loved by his wife.",
            poster_path: '/tw0ECkTsNJJJHBUqB7f2ybOD2AF.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'ko',
            genre_ids: [18, 10749],
            popularity: 11.386,
            release_date: '2020-12-03',
            video: false,
            vote_average: 5.5,
            vote_count: 5,
          },
        ],
      },
      {
        id: 2923740,
        name: 'Jerry Natanael',
        original_name: 'Jerry Natanael',
        media_type: 'person',
        adult: false,
        popularity: 0.001,
        gender: 2,
        known_for_department: 'Camera',
        profile_path: '/em0VZmvHhz9onbzTIWvEhlTiL70.jpg',
        known_for: [
          {
            backdrop_path: '/v6DIIT4UmLhy80wGf3wdz2aUR0N.jpg',
            id: 1014557,
            title: 'Familiar',
            original_title: 'Familiar',
            overview:
              "Stories about mothers and sons striving to appreciate, understand, and accept each other – navigating the twists and turns of today's family life.",
            poster_path: '/nAj2mFByjmUQJWTdTqKx88U70me.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'id',
            genre_ids: [18, 10751],
            popularity: 2.909,
            release_date: '2022-08-25',
            video: false,
            vote_average: 10,
            vote_count: 1,
          },
          {
            backdrop_path: '/j75YR3flr8jV3I62yt0x0qCAFzj.jpg',
            id: 783112,
            title: 'Rangkul',
            original_title: 'Rangkul',
            overview:
              "In the midst of a pandemic, Jaka intends to help his surroundings by providing food from his home. This is opposed by Mother, who emphasizes that the economy of their small family is also unstable and forbids Jaka to give anymore. With his mother's disapproval, Jaka faces the biggest dilemma of his life: Morals or Family.",
            poster_path: '/pgDQR1rFPfrjsI6ETzSbIDNJywv.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'id',
            genre_ids: [18],
            popularity: 1.622,
            release_date: '2020-11-15',
            video: false,
            vote_average: 0,
            vote_count: 0,
          },
          {
            backdrop_path: '/mYPPr8t3z0t5M6EywHd8qFzIFkD.jpg',
            id: 1317473,
            title: 'Playing Victim',
            original_title: 'Playing Victim',
            overview:
              'Playing Victim tells a story of a career woman named Rina who for the first time in her life, feels love and connection from a man and aspiring musician, Rifka.  However, their relationship lies in Limbo as Rifka seems to be hiding a secret, one that comes from his own past.',
            poster_path: '/aQDxrzTJqVR2YcfKhIk0MTynnCl.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'id',
            genre_ids: [18, 10749],
            popularity: 2.652,
            release_date: '2024-08-01',
            video: false,
            vote_average: 0,
            vote_count: 0,
          },
        ],
      },
      {
        id: 1622390,
        name: 'Lee Chae-dam',
        original_name: 'Lee Chae-dam',
        media_type: 'person',
        adult: false,
        popularity: 18.151,
        gender: 1,
        known_for_department: 'Acting',
        profile_path: '/7wMyr6F3yzvbSpu2XMxSW3vObED.jpg',
        known_for: [
          {
            backdrop_path: '/AaUpn8zfBmCy6TRNcS29yLWmEh1.jpg',
            id: 853033,
            title: 'Adultery Alumni Association 2',
            original_title: '불륜 동창회 2',
            overview:
              'Hye Jin, Hee Kyung, and Han Hee who are among the high school alumni. They met at the alumni meeting and heard that the male alumni who did not have a chance to study during their school days were greatly successful as an investment company. And after seeing the settlement a few days later, I am happy to share my memories, but in fact, their purpose (?) Is separate. They are difficult to afford, and they want to get help from Zhengzhou. Since then, Zhengzhou has been enjoying the love of female alumni.',
            poster_path: '/wJHAEuL4ObSAp33T2iADrti0fAM.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'ko',
            genre_ids: [18, 10749],
            popularity: 28.098,
            release_date: '2019-02-18',
            video: false,
            vote_average: 4.417,
            vote_count: 36,
          },
          {
            backdrop_path: '/prrUPAdSh7KLkOD3Hk8rfn6SF0p.jpg',
            id: 430384,
            title: "My Wife's Sister",
            original_title: '내 아내의 언니',
            overview:
              "Ji-seon is living with her sister and her husband after a divorce. Her sister Ji-yeong leaves for a work trip and Ji-seon is at home all alone with her brother-in-law. The two can't hide their sexual passion and they cross the line. Every time Ji-yeong leaves, the two enjoy risky sex...",
            poster_path: '/s1h6kr74MuJEWz3fl82NJVt7cnH.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'ko',
            genre_ids: [10749, 10751, 18],
            popularity: 25.003,
            release_date: '2016-12-20',
            video: false,
            vote_average: 5.1,
            vote_count: 15,
          },
          {
            backdrop_path: '/y7YOnq4PxKaELAMvns0x351cpNQ.jpg',
            id: 701561,
            title: "Lee Chaedam's G-Spot",
            original_title: '이채담의 지스팟',
            overview:
              'An honest, open look at the sex life of erotic film actress Lee Chae-dam. She reveals her first love, her first experience, her first film, her sex lifestyle, and her love of her body.',
            poster_path: '/tnxbYOlkXbuSXZWfHYOy4l4V51h.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'ko',
            genre_ids: [],
            popularity: 11.262,
            release_date: '2017-10-26',
            video: false,
            vote_average: 5.5,
            vote_count: 11,
          },
        ],
      },
      {
        id: 30614,
        name: 'Ryan Gosling',
        original_name: 'Ryan Gosling',
        media_type: 'person',
        adult: false,
        popularity: 39.417,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/lyUyVARQKhGxaxy0FbPJCQRpiaW.jpg',
        known_for: [
          {
            backdrop_path: '/nofXR1TN1vgGjdfnwGQwFaAWBaY.jpg',
            id: 313369,
            title: 'La La Land',
            original_title: 'La La Land',
            overview:
              'Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.',
            poster_path: '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [35, 18, 10749, 10402],
            popularity: 109.019,
            release_date: '2016-11-29',
            video: false,
            vote_average: 7.901,
            vote_count: 16477,
          },
          {
            backdrop_path: '/ilRyazdMJwN05exqhwK4tMKBYZs.jpg',
            id: 335984,
            title: 'Blade Runner 2049',
            original_title: 'Blade Runner 2049',
            overview:
              "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
            poster_path: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [878, 18],
            popularity: 213.526,
            release_date: '2017-10-04',
            video: false,
            vote_average: 7.562,
            vote_count: 13276,
          },
          {
            backdrop_path: '/1oaLxMtdn47TWdaty8BwdU4oXhV.jpg',
            id: 64690,
            title: 'Drive',
            original_title: 'Drive',
            overview:
              "Driver is a skilled Hollywood stuntman who moonlights as a getaway driver for criminals. Though he projects an icy exterior, lately he's been warming up to a pretty neighbor named Irene and her young son, Benicio. When Irene's husband gets out of jail, he enlists Driver's help in a million-dollar heist. The job goes horribly wrong, and Driver must risk his life to protect Irene and Benicio from the vengeful masterminds behind the robbery.",
            poster_path: '/602vevIURmpDfzbnv5Ubi6wIkQm.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [18, 53, 80],
            popularity: 50.943,
            release_date: '2011-09-15',
            video: false,
            vote_average: 7.6,
            vote_count: 12321,
          },
        ],
      },
      {
        id: 1158,
        name: 'Al Pacino',
        original_name: 'Al Pacino',
        media_type: 'person',
        adult: false,
        popularity: 47.022,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/2dGBb1fOcNdZjtQToVPFxXjm4ke.jpg',
        known_for: [
          {
            backdrop_path: '/b6w7gKLQLS2zw4JK0XmKgQ4gnzr.jpg',
            id: 240,
            title: 'The Godfather Part II',
            original_title: 'The Godfather Part II',
            overview:
              'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
            poster_path: '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [18, 80],
            popularity: 83.263,
            release_date: '1974-12-20',
            video: false,
            vote_average: 8.577,
            vote_count: 12127,
          },
          {
            backdrop_path: '/cCvp5Sni75agCtyJkNOMapORUQV.jpg',
            id: 111,
            title: 'Scarface',
            original_title: 'Scarface',
            overview:
              'After getting a green card in exchange for assassinating a Cuban government official, Tony Montana stakes a claim on the drug trade in Miami. Viciously murdering anyone who stands in his way, Tony eventually becomes the biggest drug lord in the state, controlling nearly all the cocaine that comes through Miami. But increased pressure from the police, wars with Colombian drug cartels and his own drug-fueled paranoia serve to fuel the flames of his eventual downfall.',
            poster_path: '/iQ5ztdjvteGeboxtmRdXEChJOHh.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [28, 80, 18],
            popularity: 90.134,
            release_date: '1983-12-09',
            video: false,
            vote_average: 8.17,
            vote_count: 11500,
          },
          {
            backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
            id: 238,
            title: 'The Godfather',
            original_title: 'The Godfather',
            overview:
              'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
            poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'en',
            genre_ids: [18, 80],
            popularity: 136.041,
            release_date: '1972-03-14',
            video: false,
            vote_average: 8.693,
            vote_count: 20099,
          },
        ],
      },
      {
        id: 57607,
        name: 'Stephen Chow',
        original_name: '周星馳',
        media_type: 'person',
        adult: false,
        popularity: 51.227,
        gender: 2,
        known_for_department: 'Acting',
        profile_path: '/j5DWs54BGZfp92G43c9OyHPvkNG.jpg',
        known_for: [
          {
            backdrop_path: '/zNOfW35hBXPIzM5BIl7gptuW0EA.jpg',
            id: 9470,
            title: 'Kung Fu Hustle',
            original_title: '功夫',
            overview:
              "It's the 1940s, and the notorious Axe Gang terrorizes Shanghai. Small-time criminals Sing and Bone hope to join, but they only manage to make lots of very dangerous enemies. Fortunately for them, kung fu masters and hidden strength can be found in unlikely places. Now they just have to take on the entire Axe Gang.",
            poster_path: '/exbyTbrvRUDKN2mcNEuVor4VFQW.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'cn',
            genre_ids: [28, 35, 80, 14],
            popularity: 44.724,
            release_date: '2004-02-10',
            video: false,
            vote_average: 7.443,
            vote_count: 2699,
          },
          {
            backdrop_path: '/tkxYmE3HzHy7E39zY3VvQ0k0VLU.jpg',
            id: 11770,
            title: 'Shaolin Soccer',
            original_title: '少林足球',
            overview:
              'A young Shaolin follower reunites with his discouraged brothers to form a soccer team using their martial art skills to their advantage.',
            poster_path: '/kVpq68NxChzynK7otaymRSaWR8p.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'cn',
            genre_ids: [28, 35],
            popularity: 59.997,
            release_date: '2001-07-05',
            video: false,
            vote_average: 7.118,
            vote_count: 2181,
          },
          {
            backdrop_path: '/7y0ol1zsvs0GbYR0BdTvWdOIDHo.jpg',
            id: 13688,
            title: 'CJ7',
            original_title: '長江七號',
            overview:
              'A poor construction worker, who struggles to keep his son in private school, mistakes an orb he finds in a junkjard for a toy which proves to be much, much more once the young boy starts to play with it.',
            poster_path: '/sRzSfpSb3wYYshbaiMRIuFCJJGU.jpg',
            media_type: 'movie',
            adult: false,
            original_language: 'cn',
            genre_ids: [35, 18, 10751, 14, 878],
            popularity: 30.939,
            release_date: '2008-01-30',
            video: false,
            vote_average: 7.3,
            vote_count: 673,
          },
        ],
      },
    ],
    movies: [
      {
        backdrop_path: '/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg',
        id: 1048241,
        title: 'My Spy the Eternal City',
        original_title: 'My Spy the Eternal City',
        overview:
          'JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.',
        poster_path: '/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [28, 35],
        popularity: 274.59,
        release_date: '2024-07-18',
        video: false,
        vote_average: 7.045,
        vote_count: 66,
      },
      {
        backdrop_path: '/fpo2qM5b4gTF5EHuYGlxsDIlZOj.jpg',
        id: 774531,
        title: 'Young Woman and the Sea',
        original_title: 'Young Woman and the Sea',
        overview:
          'The True Story of a young Trudy Ederle, who fights to overcome adversity and the animosity of a patriarchal society to rise through the ranks of the Olympic swimming team. Against all odds, she sets her sights on completing a staggering and dangerous journey — to become the first woman to swim across the brutal 21-mile stretch known as The English Channel.',
        poster_path: '/bZlecCuBVvKuarNGvchBwaOsQ3c.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [36, 18],
        popularity: 49.342,
        release_date: '2024-05-31',
        video: false,
        vote_average: 7.641,
        vote_count: 46,
      },
      {
        backdrop_path: '/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg',
        id: 718821,
        title: 'Twisters',
        original_title: 'Twisters',
        overview:
          'As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.',
        poster_path: '/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [28, 12, 53],
        popularity: 771.648,
        release_date: '2024-07-10',
        video: false,
        vote_average: 7.386,
        vote_count: 132,
      },
      {
        backdrop_path: '/peE1ax04MnTQ9ChDryoDNF95r5.jpg',
        id: 1255350,
        title: 'Find Me Falling',
        original_title: 'Find Me Falling',
        overview:
          'After a failed comeback album, rock star John Allman escapes to a dreamy Mediterranean island, only to discover that his new cliffside home has an unfortunate notoriety that attracts unwanted visitors and an old flame.',
        poster_path: '/pMWpIPJgL4lYNKxSVMRDFWITeMW.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [10749, 35, 10402],
        popularity: 106.83,
        release_date: '2024-07-19',
        video: false,
        vote_average: 6,
        vote_count: 11,
      },
      {
        backdrop_path: '/9l1eZiJHmhr5jIlthMdJN5WYoff.jpg',
        id: 533535,
        title: 'Deadpool & Wolverine',
        original_title: 'Deadpool & Wolverine',
        overview:
          'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
        poster_path: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [878, 28, 35],
        popularity: 849.864,
        release_date: '2024-07-24',
        video: false,
        vote_average: 8.5,
        vote_count: 10,
      },
      {
        backdrop_path: '/wkPPRIducGfsbaUPsWfw0MCQdX7.jpg',
        id: 1051891,
        title: 'Thelma',
        original_title: 'Thelma',
        overview:
          'When 93-year-old Thelma Post gets duped by a phone scammer pretending to be her grandson, she sets out on a treacherous quest across the city to reclaim what was taken from her.',
        poster_path: '/rUcuageYgv9SsJoWuc0seRWG6JC.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [28, 35, 12],
        popularity: 46.644,
        release_date: '2024-06-21',
        video: false,
        vote_average: 7.8,
        vote_count: 17,
      },
      {
        backdrop_path: '/fqv8v6AycXKsivp1T5yKtLbGXce.jpg',
        id: 653346,
        title: 'Kingdom of the Planet of the Apes',
        original_title: 'Kingdom of the Planet of the Apes',
        overview:
          "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
        poster_path: '/gKkl37BQuKTanygYQG1pyYgLVgf.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [878, 12, 28],
        popularity: 1631,
        release_date: '2024-05-08',
        video: false,
        vote_average: 7.138,
        vote_count: 1966,
      },
      {
        backdrop_path: '/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg',
        id: 1022789,
        title: 'Inside Out 2',
        original_title: 'Inside Out 2',
        overview:
          "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
        poster_path: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [16, 10751, 12, 35],
        popularity: 5571.077,
        release_date: '2024-06-11',
        video: false,
        vote_average: 7.683,
        vote_count: 1943,
      },
      {
        backdrop_path: '/dsGwCEO8tda4FlgHKvL95f0oQbH.jpg',
        id: 1209290,
        title: 'Justice League: Crisis on Infinite Earths Part Three',
        original_title: 'Justice League: Crisis on Infinite Earths Part Three',
        overview:
          'Now fully revealed as the ultimate threat to existence, the Anti-Monitor wages an unrelenting attack on the surviving Earths that struggle for survival in a pocket universe. One by one, these worlds and all their inhabitants are vaporized! On the planets that remain, even time itself is shattered, and heroes from the past join the Justice League and their rag-tag allies against the epitome of evil. But as they make their last stand, will the sacrifice of the superheroes be enough to save us all?',
        poster_path: '/a3q8NkM8uTh9E23VsbUOdDSbBeN.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [16, 878, 28],
        popularity: 439.054,
        release_date: '2024-07-16',
        video: false,
        vote_average: 7.406,
        vote_count: 53,
      },
      {
        backdrop_path: '/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg',
        id: 786892,
        title: 'Furiosa: A Mad Max Saga',
        original_title: 'Furiosa: A Mad Max Saga',
        overview:
          'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.',
        poster_path: '/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [28, 12, 878],
        popularity: 1872.179,
        release_date: '2024-05-22',
        video: false,
        vote_average: 7.65,
        vote_count: 2224,
      },
      {
        backdrop_path: '/8UOAYjhwSF3aPZhm6wgLuyHRyrR.jpg',
        id: 932086,
        title: 'Horizon: An American Saga - Chapter 1',
        original_title: 'Horizon: An American Saga - Chapter 1',
        overview:
          'Follow the story of how the Old West was won—and lost—through the blood, sweat and tears of many. Spanning 15 years before, during and following the Civil War from 1859 to 1874, embark on an emotional journey across a country at war with itself, experienced through the lens of families, friends and foes all attempting to discover what it truly means to be the United States of America.',
        poster_path: '/hqDkO0W9uk4aiwzn3pTeLO7NPZD.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [37, 18],
        popularity: 515.866,
        release_date: '2024-06-26',
        video: false,
        vote_average: 7.024,
        vote_count: 104,
      },
      {
        backdrop_path: '/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg',
        id: 519182,
        title: 'Despicable Me 4',
        original_title: 'Despicable Me 4',
        overview:
          'Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.',
        poster_path: '/3w84hCFJATpiCO5g8hpdWVPBbmq.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [16, 10751, 35, 28],
        popularity: 4439.3,
        release_date: '2024-06-20',
        video: false,
        vote_average: 7.381,
        vote_count: 340,
      },
      {
        backdrop_path: '/5Eip60UDiPLASyKjmHPMruggTc4.jpg',
        id: 1041613,
        title: 'Immaculate',
        original_title: 'Immaculate',
        overview:
          'An American nun embarks on a new journey when she joins a remote convent in the Italian countryside. However, her warm welcome quickly turns into a living nightmare when she discovers her new home harbours a sinister secret and unspeakable horrors.',
        poster_path: '/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [27, 9648, 53],
        popularity: 417.723,
        release_date: '2024-03-20',
        video: false,
        vote_average: 6.321,
        vote_count: 718,
      },
      {
        backdrop_path: '/a4IWRYNMNMszIkRbEIiNsRg6cvt.jpg',
        id: 929590,
        title: 'Civil War',
        original_title: 'Civil War',
        overview:
          'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.',
        poster_path: '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [10752, 28, 18],
        popularity: 793.972,
        release_date: '2024-04-10',
        video: false,
        vote_average: 6.988,
        vote_count: 1930,
      },
      {
        backdrop_path: '/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg',
        id: 974262,
        title: 'Descendants: The Rise of Red',
        original_title: 'Descendants: The Rise of Red',
        overview:
          "After the Queen of Hearts incites a coup on Auradon, her rebellious daughter Red and Cinderella's perfectionist daughter Chloe join forces and travel back in time to try to undo the traumatic event that set Red's mother down her villainous path.",
        poster_path: '/8fYluTtB3b3HKO7KQa5tzrvGaps.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [14, 12, 10751, 35],
        popularity: 2030.613,
        release_date: '2024-07-11',
        video: false,
        vote_average: 7.257,
        vote_count: 148,
      },
      {
        backdrop_path: '/Avtx5jsdPuDa091jvx2Lye3ygke.jpg',
        id: 1226578,
        title: 'Longlegs',
        original_title: 'Longlegs',
        overview:
          'In pursuit of a serial killer, an FBI agent uncovers a series of occult clues that she must solve to end his terrifying killing spree.',
        poster_path: '/dLAP1apgFIoBoPNw4HJLVACSu7u.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [80, 27, 53],
        popularity: 190.849,
        release_date: '2024-07-10',
        video: false,
        vote_average: 6.806,
        vote_count: 111,
      },
      {
        backdrop_path: '/60qVuzQOKgyD57tsgBceT5ScCSX.jpg',
        id: 1214488,
        title: 'Skywalkers: A Love Story',
        original_title: 'Skywalkers: A Love Story',
        overview:
          "Two real-life daredevils test the limits of their love and trust by illegally scaling one of the world's tallest buildings to perform an acrobatic stunt.",
        poster_path: '/7A4x0D1gNTpmMn9E9BW9hWiaOkv.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [99, 10749, 53],
        popularity: 28.489,
        release_date: '2024-07-12',
        video: false,
        vote_average: 7.9,
        vote_count: 15,
      },
      {
        backdrop_path: '/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg',
        id: 748783,
        title: 'The Garfield Movie',
        original_title: 'The Garfield Movie',
        overview:
          'Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.',
        poster_path: '/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [16, 35, 10751, 12],
        popularity: 2173.538,
        release_date: '2024-04-30',
        video: false,
        vote_average: 7.3,
        vote_count: 504,
      },
      {
        backdrop_path: '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
        id: 693134,
        title: 'Dune: Part Two',
        original_title: 'Dune: Part Two',
        overview:
          'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
        poster_path: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [878, 12],
        popularity: 382.953,
        release_date: '2024-02-27',
        video: false,
        vote_average: 8.166,
        vote_count: 4867,
      },
      {
        backdrop_path: '/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg',
        id: 7451,
        title: 'xXx',
        original_title: 'xXx',
        overview:
          'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
        poster_path: '/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg',
        media_type: 'movie',
        adult: false,
        original_language: 'en',
        genre_ids: [28, 12, 53, 80],
        popularity: 438.996,
        release_date: '2002-08-09',
        video: false,
        vote_average: 5.9,
        vote_count: 4120,
      },
    ],
    series: [
      {
        backdrop_path: '/7cqKGQMnNabzOpi7qaIgZvQ7NGV.jpg',
        id: 76479,
        name: 'The Boys',
        original_name: 'The Boys',
        overview:
          'A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.',
        poster_path: '/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [10765, 10759],
        popularity: 2947.075,
        first_air_date: '2019-07-25',
        vote_average: 8.5,
        vote_count: 9997,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/3m9t52rcLdQuDNEnyhtpn9y9CGp.jpg',
        id: 218589,
        name: 'Those About to Die',
        original_name: 'Those About to Die',
        overview:
          'Within the spectacular, complex and corrupt world of gladiatorial sports in Ancient Rome, follow an ensemble of diverse characters across the many layers of Roman society where sports, politics and business intersect and collide.',
        poster_path: '/gvz0m4MJ8sAj6yMcQdwN07bNjRY.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [18],
        popularity: 288.757,
        first_air_date: '2024-07-18',
        vote_average: 8.2,
        vote_count: 12,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/mceCXNTny6a5F3rQgShLoyARw4l.jpg',
        id: 96648,
        name: 'Sweet Home',
        original_name: '스위트홈',
        overview:
          'As humans turn into savage monsters and the world plunges into terror, a handful of survivors fight for their lives — and to hold on to their humanity.',
        poster_path: '/7wbPHetLZnyL6hwqrfEPnLNKnXu.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ko',
        genre_ids: [18, 10765, 80],
        popularity: 907.785,
        first_air_date: '2020-12-18',
        vote_average: 8.3,
        vote_count: 1274,
        origin_country: ['KR'],
      },
      {
        backdrop_path: '/xFJS2FeCfCztFWO9yEW0RV2uFz.jpg',
        id: 77169,
        name: 'Cobra Kai',
        original_name: 'Cobra Kai',
        overview:
          'This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.',
        poster_path: '/6GDW4EsgsXlYrL1ASb5eCHQK4er.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [10759, 18, 35],
        popularity: 2584.134,
        first_air_date: '2018-05-02',
        vote_average: 8.216,
        vote_count: 6029,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/iYQlpBH9RHmoDVcvGsvNpG3Ikx5.jpg',
        id: 120549,
        name: 'Lady in the Lake',
        original_name: 'Lady in the Lake',
        overview:
          'When the disappearance of a young girl grips the city of Baltimore in 1966, the lives of two women converge on a fatal collision course.',
        poster_path: '/cK0zAfFHfpSZJ5e9yhm2jRJJ6Zj.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [18, 80],
        popularity: 140.435,
        first_air_date: '2024-07-18',
        vote_average: 7.5,
        vote_count: 8,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/kwronSXO1ogMqHHFvY2eBxfFLdn.jpg',
        id: 114479,
        name: 'The Acolyte',
        original_name: 'The Acolyte',
        overview:
          'A hundred years before the rise of the Empire, the Jedi Order and the Galactic Republic have prospered for centuries without war. During this time, an investigation into a shocking crime spree pits a Jedi Master against a dangerous warrior from his past.',
        poster_path: '/fW2nOB5EXEOh64qufAxeW4AU3AB.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [9648, 10765],
        popularity: 572.82,
        first_air_date: '2024-06-04',
        vote_average: 5.7,
        vote_count: 350,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/ueVgPm1VN6ZgEtzj9WUOpSMj4d0.jpg',
        id: 258759,
        name: 'Strange Tales of Tang Dynasty II To the West',
        original_name: '唐朝诡事录之西行',
        overview: '',
        poster_path: '/usptf7Hj21E34GsIOycKJjV4Arg.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'zh',
        genre_ids: [9648],
        popularity: 56.703,
        first_air_date: '2024-07-18',
        vote_average: 6,
        vote_count: 1,
        origin_country: ['CN'],
      },
      {
        backdrop_path: '/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg',
        id: 94997,
        name: 'House of the Dragon',
        original_name: 'House of the Dragon',
        overview:
          'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne. But when Viserys later fathers a son, the court is shocked when Rhaenyra retains her status as his heir, and seeds of division sow friction across the realm.',
        poster_path: '/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [10765, 18, 10759],
        popularity: 3277.952,
        first_air_date: '2022-08-21',
        vote_average: 8.417,
        vote_count: 4446,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/m2D5bhoAB0ewe42m8rfIl0a1ahM.jpg',
        id: 211089,
        name: 'Strange Tales Of Tang Dynasty',
        original_name: '唐朝诡事录',
        overview:
          "When the dark evil immortal descends from the heaven, and the mysterious underground ghost palace was revealed, a strange herb named the Black Tea suddenly took Chang'an City by storm. However, no one knows whether it is a healthy medicine or one that could harm people. Cases of missing brides in Chang'an City began occurring one after another, which seems to be inextricably linked to the black tea...  Ling Feng, general of the Jin Wu guards was tasked to investigate these cases. On his journey, he meets his strongest opponent in Su Wu Ming, the disciple of Di Ren Jie. The two of them work together to solve these mysterious cases.",
        poster_path: '/y8a0sXfO1tn5KGH6mRVn7FnPdkW.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'zh',
        genre_ids: [9648, 80, 10759],
        popularity: 427.673,
        first_air_date: '2022-09-27',
        vote_average: 8.2,
        vote_count: 13,
        origin_country: ['CN'],
      },
      {
        backdrop_path: '/us2E4vqo5zJrUledrNX1KTpk3gT.jpg',
        id: 230424,
        name: 'Betty la Fea, the Story Continues',
        original_name: 'Betty la fea, la historia continúa',
        overview:
          'While an empowered and wiser Betty works hard on rebuilding her relationship with her teenage daughter Mila, her relationship with Armando begins to deteriorate, making her question if she made the right decision 20 years ago.',
        poster_path: '/sgCcmsJ4aKAK8QwrbG6RLYxxFAj.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'es',
        genre_ids: [10766, 35],
        popularity: 362.526,
        first_air_date: '2024-07-19',
        vote_average: 8.429,
        vote_count: 28,
        origin_country: ['CO'],
      },
      {
        backdrop_path: '/2WBO3C7CjsOTT5wgi9Inn5iQhVv.jpg',
        id: 46195,
        name: 'Monogatari',
        original_name: '化物語',
        overview:
          'Although there are still traces of the brief period he became a vampire, third-year high school student Koyomi Araragi is human again. He happens upon others with their own supernatural problems and finds that he can empathize. Koyomi becomes involved in their lives, seeking to help them and occasionally asking for advice from Meme Oshino, the homeless man who helped him become human again.',
        poster_path: '/zCEjjb1NH3LLsWeZx47wOeqkezf.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ja',
        genre_ids: [16, 35, 18, 9648],
        popularity: 434.77,
        first_air_date: '2009-07-03',
        vote_average: 8.133,
        vote_count: 446,
        origin_country: ['JP'],
      },
      {
        backdrop_path: '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
        id: 37854,
        name: 'One Piece',
        original_name: 'ワンピース',
        overview:
          'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
        poster_path: '/e3NBGiAifW9Xt8xD5tpARskjccO.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ja',
        genre_ids: [10759, 35, 16],
        popularity: 146.921,
        first_air_date: '1999-10-20',
        vote_average: 8.721,
        vote_count: 4525,
        origin_country: ['JP'],
      },
      {
        backdrop_path: '/wHNwlE6ftEpgjVbdhLXOtv1hLs0.jpg',
        id: 136315,
        name: 'The Bear',
        original_name: 'The Bear',
        overview:
          'Carmy, a young fine-dining chef, comes home to Chicago to run his family sandwich shop. As he fights to transform the shop and himself, he works alongside a rough-around-the-edges crew that ultimately reveal themselves as his chosen family.',
        poster_path: '/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [18, 35],
        popularity: 444.281,
        first_air_date: '2022-06-23',
        vote_average: 8.289,
        vote_count: 966,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/l31qDy1jqKcoXmCkcAvDrqebwkX.jpg',
        id: 250850,
        name: 'Master of the House',
        original_name: 'สืบสันดาน',
        overview:
          'A family enters a power struggle following the death of their patriarch, who leaves behind his diamond empire — and the housekeeper he recently married.',
        poster_path: '/bJnrzJWTFXUN64EUiFzHCMj9SfW.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'th',
        genre_ids: [18, 9648],
        popularity: 264.496,
        first_air_date: '2024-07-18',
        vote_average: 7.75,
        vote_count: 4,
        origin_country: ['TH'],
      },
      {
        backdrop_path: '/vfE3gd2VoWbJ2h5E1IOialJawgv.jpg',
        id: 70722,
        name: 'Momokyun Sword',
        original_name: 'モモキュンソード',
        overview:
          "Momoko is a beautiful young sword fighter who was born inside a peach. She lives with her constant companions—the dog god Inugami, the monkey god Sarugami, and the pheasant god Kijigami—in a peaceful paradise. However, a demon army led by devil king invades the paradise and steals the precious treasure that protects Momoko's land. To retrieve the treasure and save the people, Momoko embarks on a great adventure with her three companions.",
        poster_path: '/tg6HZ5SKGv7ezXxjwXn24MHYlnr.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ja',
        genre_ids: [10759, 16],
        popularity: 57.018,
        first_air_date: '2014-07-09',
        vote_average: 7.1,
        vote_count: 11,
        origin_country: ['JP'],
      },
      {
        backdrop_path: '/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg',
        id: 1399,
        name: 'Game of Thrones',
        original_name: 'Game of Thrones',
        overview:
          "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
        poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [10765, 18, 10759],
        popularity: 1908.623,
        first_air_date: '2011-04-17',
        vote_average: 8.453,
        vote_count: 23464,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/peENvis00Fkw27KLFuaoWsu0YnD.jpg',
        id: 79680,
        name: 'Snowpiercer',
        original_name: 'Snowpiercer',
        overview:
          'More than seven years after the world has become a frozen wasteland, the remnants of humanity inhabit a gigantic, perpetually-moving train that circles the globe as class warfare, social injustice and the politics of survival play out.',
        poster_path: '/exKzfiKzMdQBHrdd7zNmKauJkbg.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [10765],
        popularity: 472.387,
        first_air_date: '2020-05-17',
        vote_average: 7.4,
        vote_count: 1169,
        origin_country: ['US'],
      },
      {
        backdrop_path: '/gArCVC4ML529WMCEqOXbALdQbUq.jpg',
        id: 203737,
        name: 'Oshi No Ko',
        original_name: '【推しの子】',
        overview:
          'Dr. Goro is reborn as the son of the young starlet Ai Hoshino after her delusional stalker murders him. Now, he wants to help his new mother rise to the top, but what can a child do about the dark underbelly of the entertainment industry?',
        poster_path: '/rFp74PFpz14AHrtlVPrLyrSng47.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ja',
        genre_ids: [16, 18],
        popularity: 317.033,
        first_air_date: '2023-04-12',
        vote_average: 8.278,
        vote_count: 171,
        origin_country: ['JP'],
      },
      {
        backdrop_path: '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
        id: 1429,
        name: 'Attack on Titan',
        original_name: '進撃の巨人',
        overview:
          'Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.',
        poster_path: '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'ja',
        genre_ids: [16, 10765, 10759],
        popularity: 150.795,
        first_air_date: '2013-04-07',
        vote_average: 8.661,
        vote_count: 6174,
        origin_country: ['JP'],
      },
      {
        backdrop_path: '/qzi8rTS2KpkrYNWxC1tt7xkRlTY.jpg',
        id: 156933,
        name: 'Presumed Innocent',
        original_name: 'Presumed Innocent',
        overview:
          "A horrific murder upends the Chicago Prosecuting Attorney's Office when one of its own is suspected of the crime—leaving the accused fighting to keep his family together.",
        poster_path: '/7MXg0BxuSRWz2yKc03M40du2mrc.jpg',
        media_type: 'tv',
        adult: false,
        original_language: 'en',
        genre_ids: [18, 9648],
        popularity: 606.997,
        first_air_date: '2024-06-11',
        vote_average: 8.158,
        vote_count: 114,
        origin_country: ['US'],
      },
    ],
  };

  protected headerButtons: HeaderButton[] = [
    {
      type: 'icon',
      iconPath: '../../../../assets/icons/home-header/Github-solid.svg',
      anchor: {
        urlType: 'external',
        path: 'https://github.com/Scottify20/salida',
        target: '_blank',
      },
    },
    {
      type: 'text',
      text: 'Logo',
      anchor: {
        urlType: 'internal',
        path: '/',
        target: '_self',
      },
    },
    {
      type: 'icon',
      iconPath: '../../../../assets/icons/home-header/User-solid.svg',
      actionCallback: () => console.log('profile clicked'),
    },
  ];

  protected movies: TmdbEntityForCard[] = this.tmdbEntities.movies.map(
    (movie) => ({
      name: movie.title,
      image_path: movie.poster_path,
    })
  );
  protected series: TmdbEntityForCard[] = this.tmdbEntities.series.map(
    (series) => ({
      name: series.name,
      image_path: series.poster_path,
    })
  );

  protected persons: TmdbEntityForCard[] = this.tmdbEntities.persons.map(
    (person) => ({
      name: person.name,
      image_path: person.profile_path,
    })
  );

  @ViewChild(HeroCardsComponent) heroCards!: HeroCardsComponent;

  ngAfterViewInit(): void {
    this.heroCards.startCardsScrollBasedAnimation();
  }
  ngOnDestroy(): void {
    this.heroCards.stopCardsScrollBasedAnimation();
  }

  sampleCallback() {}
}

export interface TmdbEntityForCard {
  name: string;
  image_path: string;
}
